const PROHIBITED_MARKET_KEYS=new Set(['odds','price','decimal_price','american_price','implied_probability','sportsbook','bookmaker','market_line','consensus_line','bet365','sportsbet','tab','ladbrokes','unibet']);
const VALID_RUN_MODES=new Set(['ALL','SHOOTING_ONLY','SAVES_ONLY']);
const VALID_AVAILABILITY=new Set(['ACTIVE','PROBABLE','QUESTIONABLE','DOUBTFUL','OUT','UNKNOWN']);
const VALID_PLAYER_TYPES=new Set(['OUTFIELD','GOALKEEPER']);
const VALID_CONFIDENCE=new Set(['A','B','C']);
const VALID_FRAGILITY=new Set(['LOW','MEDIUM','HIGH']);
const HASH64=/^[0-9a-f]{64}$/;

export function requireThat(condition,message){if(!condition)throw new Error(message);}
function finite(value,label){const n=Number(value);requireThat(Number.isFinite(n),`${label} must be finite`);return n;}
function nonnegative(value,label){const n=finite(value,label);requireThat(n>=0,`${label} must be nonnegative`);return n;}
function positive(value,label){const n=nonnegative(value,label);requireThat(n>0,`${label} must be > 0`);return n;}
function probability(value,label){const n=nonnegative(value,label);requireThat(n<=1,`${label} must be <= 1`);return n;}
function receipt(value,label){const x=String(value||'');requireThat(HASH64.test(x),`${label} must be lowercase SHA-256`);return x;}
function iso(value,label){const x=String(value||'').trim();requireThat(x&&Number.isFinite(Date.parse(x)),`${label} must be ISO-8601`);return x;}
function httpsUrl(value,label){let url;try{url=new URL(String(value||''));}catch{throw new Error(`${label} must be absolute HTTPS URL`);}requireThat(url.protocol==='https:',`${label} must be absolute HTTPS URL`);return url.toString();}

export function marketKeyHits(value,path='root',hits=[]){
  if(Array.isArray(value)){value.forEach((item,i)=>marketKeyHits(item,`${path}[${i}]`,hits));return hits;}
  if(value&&typeof value==='object')for(const [key,item] of Object.entries(value)){const normalized=String(key).trim().toLowerCase();if(PROHIBITED_MARKET_KEYS.has(normalized))hits.push(`${path}.${key}`);marketKeyHits(item,`${path}.${key}`,hits);}return hits;
}
export function assertMarketBlind(value){const hits=marketKeyHits(value);requireThat(hits.length===0,`market-derived fields prohibited: ${hits.join(', ')}`);}

function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])]));return value;}
export async function sha256Json(value){const raw=JSON.stringify(stable(value)),hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw));return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');}

function lgamma(z){
  const p=[0.99999999999980993,676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-0.13857109526572012,9.9843695780195716e-6,1.5056327351493116e-7];
  if(z<0.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-lgamma(1-z);
  z-=1;let x=p[0];for(let i=1;i<p.length;i++)x+=p[i]/(z+i);const t=z+p.length-1.5;return 0.5*Math.log(2*Math.PI)+(z+0.5)*Math.log(t)-t+Math.log(x);
}
function nbLogPmf(k,mean,dispersion){requireThat(Number.isInteger(k)&&k>=0,'k must be nonnegative integer');nonnegative(mean,'mean');positive(dispersion,'dispersion');if(mean===0)return k===0?0:-Infinity;const r=dispersion,p=r/(r+mean);return lgamma(k+r)-lgamma(r)-lgamma(k+1)+r*Math.log(p)+k*Math.log(1-p);}
function nbPmf(k,mean,dispersion){const x=nbLogPmf(k,mean,dispersion);return x===-Infinity?0:Math.exp(x);}
export function probabilityAtLeast(threshold,mean,dispersion){if(threshold<=0)return 1;let cdf=0;for(let k=0;k<threshold;k++)cdf+=nbPmf(k,mean,dispersion);return Math.max(0,Math.min(1,1-cdf));}
function ladder(mean,dispersion,max){const out={};let prior=1;for(let k=1;k<=max;k++){const p=probabilityAtLeast(k,mean,dispersion);requireThat(p<=prior+1e-12,'ladder monotonicity failure');out[String(k)]=p;prior=p;}return out;}

function playerKey(row){const id=String(row?.player_id||'').trim();if(id)return `id:${id}`;const name=String(row?.player_name||'').toLowerCase().replace(/[^a-z0-9]+/g,'');requireThat(name,'player_id or player_name required');return `name:${name}`;}
function sourceIds(value,known,label){requireThat(Array.isArray(value)&&value.length>0,`${label} requires source ids`);const ids=value.map(x=>String(x).trim()).filter(Boolean);requireThat(ids.length>0,`${label} requires source ids`);for(const id of ids)requireThat(known.has(id),`${label} references unknown source ${id}`);return ids;}
function notes(value,label){requireThat(Array.isArray(value)&&value.some(x=>String(x).trim()),`${label} requires notes`);}

export function validateResearchContext(context){
  requireThat(context&&typeof context==='object'&&!Array.isArray(context),'research context must be object');
  requireThat(context.market_data===false,'research context must declare market_data=false');assertMarketBlind(context);
  requireThat(context.schema_version==='aleague_player_volume_research_v1','research schema_version invalid');
  const mode=String(context.run_mode||'').toUpperCase();requireThat(VALID_RUN_MODES.has(mode),'unsupported run_mode');
  requireThat(String(context.fixture_id||'').trim(),'fixture_id required');requireThat(String(context.pack_revision||'').trim(),'pack_revision required');iso(context.checked_at,'checked_at');
  const sources=context.sources;requireThat(sources&&typeof sources==='object'&&!Array.isArray(sources)&&Object.keys(sources).length>0,'sources required');const known=new Set();
  for(const [id,src] of Object.entries(sources)){requireThat(id.trim()&&src&&typeof src==='object',`invalid source ${id}`);known.add(id);httpsUrl(src.url,`sources.${id}.url`);iso(src.checked_at,`sources.${id}.checked_at`);requireThat(String(src.title||'').trim(),`sources.${id}.title required`);}
  const fixture=context.fixture_context;requireThat(fixture&&typeof fixture==='object','fixture_context required');const home=String(fixture.home_team_id||'').trim(),away=String(fixture.away_team_id||'').trim();requireThat(home&&away&&home!==away,'distinct home/away team ids required');iso(fixture.kickoff_utc,'fixture_context.kickoff_utc');sourceIds(fixture.source_ids,known,'fixture_context.source_ids');requireThat(String(fixture.status||'').trim(),'fixture status required');
  const teamIds=new Set([home,away]),teams=context.teams;requireThat(Array.isArray(teams)&&teams.length===2,'teams must contain exactly two entries');const seenTeams=new Set();for(const team of teams){const id=String(team?.team_id||'');requireThat(teamIds.has(id)&&!seenTeams.has(id),'team id invalid/duplicate');seenTeams.add(id);requireThat(String(team.team_name||'').trim(),'team_name required');sourceIds(team.source_ids,known,'team.source_ids');notes(team.notes,'team.notes');}
  requireThat(Array.isArray(context.players)&&context.players.length>0,'players required');const seen=new Set(),keeperTeams=new Set();
  for(const row of context.players){const key=playerKey(row);requireThat(!seen.has(key),`duplicate research player ${key}`);seen.add(key);const teamId=String(row.team_id||'');requireThat(teamIds.has(teamId),`${key} team invalid`);requireThat(String(row.player_name||'').trim(),`${key} name required`);const type=String(row.player_type||'').toUpperCase(),availability=String(row.availability_status||'').toUpperCase();requireThat(VALID_PLAYER_TYPES.has(type),`${key} player_type invalid`);requireThat(VALID_AVAILABILITY.has(availability),`${key} availability invalid`);sourceIds(row.availability_source_ids,known,`${key}.availability_source_ids`);
    const m=row.projected_minutes;requireThat(m&&typeof m==='object',`${key}.projected_minutes required`);const low=finite(m.low,`${key}.minutes.low`),mean=finite(m.mean,`${key}.minutes.mean`),high=finite(m.high,`${key}.minutes.high`);requireThat(0<=low&&low<=mean&&mean<=high&&high<=90,`${key} projected minutes invalid`);sourceIds(m.source_ids,known,`${key}.minutes.source_ids`);
    const role=row.role;requireThat(role&&typeof role==='object',`${key}.role required`);sourceIds(role.source_ids,known,`${key}.role.source_ids`);notes(role.notes,`${key}.role.notes`);if(type==='GOALKEEPER')requireThat(String(role.position_role||'').toUpperCase()==='GK',`${key} goalkeeper must use GK role`);else requireThat(String(role.position_role||'').toUpperCase()!=='GK',`${key} outfield cannot use GK role`);
    const stats=row.stat_context;requireThat(stats&&typeof stats==='object',`${key}.stat_context required`);const needed=type==='GOALKEEPER'?['saves']:['shots','shots_on_target'];for(const stat of needed){requireThat(stats[stat]&&typeof stats[stat]==='object',`${key}.${stat} stat context required`);sourceIds(stats[stat].source_ids,known,`${key}.${stat}.source_ids`);notes(stats[stat].notes,`${key}.${stat}.notes`);}if(type==='GOALKEEPER'&&availability!=='OUT')keeperTeams.add(teamId);
  }
  if(mode==='ALL'||mode==='SAVES_ONLY')requireThat(keeperTeams.size===2&&[...teamIds].every(x=>keeperTeams.has(x)),'save modeling requires non-OUT goalkeeper for each team');return context;
}

function allocation(teamMean,models,unmodelledWeight){const weights=new Map();let denom=nonnegative(unmodelledWeight,'unmodelled_weight');for(const m of models){const w=nonnegative(m.shots_per90_prior,`${m.key}.shots_per90_prior`)*(m.minutes_mean/90)*positive(m.role_multiplier,`${m.key}.role_multiplier`);weights.set(m.key,w);denom+=w;}requireThat(denom>0,'shot allocation denominator must be >0');const means=new Map();let sum=teamMean*unmodelledWeight/denom;for(const [key,w] of weights){const mu=teamMean*w/denom;means.set(key,mu);sum+=mu;}requireThat(Math.abs(sum-teamMean)<=1e-6*Math.max(1,teamMean),'shot allocation mismatch');return {means,unmodelled:teamMean*unmodelledWeight/denom};}

export async function buildFrozenFixture(researchContext,teamModels,outfieldModels,goalkeeperModels,{frozenAt=null}={}){
  validateResearchContext(researchContext);assertMarketBlind(teamModels);assertMarketBlind(outfieldModels);assertMarketBlind(goalkeeperModels);
  const fixture=researchContext.fixture_context,teamIds=new Set([String(fixture.home_team_id),String(fixture.away_team_id)]),known=new Set(Object.keys(researchContext.sources)),mode=String(researchContext.run_mode).toUpperCase();const research=new Map(researchContext.players.map(p=>[playerKey(p),p]));
  requireThat(Array.isArray(teamModels)&&teamModels.length===2,'team_models must contain two teams');const tmap=new Map();for(const [i,m] of teamModels.entries()){const id=String(m?.team_id||'');requireThat(teamIds.has(id)&&!tmap.has(id),`team_models[${i}] id invalid/duplicate`);tmap.set(id,{team_id:id,shot_mean:nonnegative(m.shot_mean,`${id}.shot_mean`),shot_dispersion:positive(m.shot_dispersion,`${id}.shot_dispersion`),unmodelled_weight:nonnegative(m.unmodelled_weight,`${id}.unmodelled_weight`),unmodelled_p_sot:probability(m.unmodelled_p_sot,`${id}.unmodelled_p_sot`),evidence_source_ids:sourceIds(m.evidence_source_ids,known,`${id}.evidence_source_ids`),quant_input_receipt_sha256:receipt(m.quant_input_receipt_sha256,`${id}.quant_input_receipt_sha256`)});}
  const byTeam=new Map([...teamIds].map(id=>[id,[]])),seen=new Set();for(const m of outfieldModels||[]){const key=playerKey(m);requireThat(!seen.has(key),`duplicate modeled player ${key}`);seen.add(key);const rp=research.get(key);requireThat(rp&&String(rp.player_type).toUpperCase()==='OUTFIELD',`${key} missing/mismatched research`);requireThat(String(rp.availability_status).toUpperCase()!=='OUT',`cannot model OUT player ${key}`);const teamId=String(m.team_id||'');requireThat(teamId===String(rp.team_id)&&teamIds.has(teamId),`${key} team mismatch`);const roleMultiplier=positive(m.role_multiplier,`${key}.role_multiplier`);requireThat(roleMultiplier<=2,`${key}.role_multiplier exceeds bound`);const confidence=String(m.confidence||'').toUpperCase(),fragility=String(m.fragility||'').toUpperCase();requireThat(VALID_CONFIDENCE.has(confidence),`${key}.confidence invalid`);requireThat(VALID_FRAGILITY.has(fragility),`${key}.fragility invalid`);byTeam.get(teamId).push({key,player_id:String(m.player_id||rp.player_id||''),player_name:String(rp.player_name),team_id:teamId,minutes_mean:Number(rp.projected_minutes.mean),shots_per90_prior:nonnegative(m.shots_per90_prior,`${key}.shots_per90_prior`),role_multiplier:roleMultiplier,p_sot_given_shot:probability(m.p_sot_given_shot,`${key}.p_sot_given_shot`),shot_dispersion:positive(m.shot_dispersion,`${key}.shot_dispersion`),confidence,fragility,evidence_source_ids:sourceIds(m.evidence_source_ids,known,`${key}.evidence_source_ids`),quant_input_receipt_sha256:receipt(m.quant_input_receipt_sha256,`${key}.quant_input_receipt_sha256`)});}
  if(mode==='ALL'||mode==='SHOOTING_ONLY')for(const id of teamIds)requireThat(byTeam.get(id).length>0,`shooting freeze requires outfield players for team ${id}`);
  const frozenOutfield=[],teamEnvironment={};for(const teamId of [...teamIds].sort()){const tm=tmap.get(teamId),models=byTeam.get(teamId),a=allocation(tm.shot_mean,models,tm.unmodelled_weight);let modeledSot=0;for(const m of models){const muShots=a.means.get(m.key),muSot=muShots*m.p_sot_given_shot;modeledSot+=muSot;const heads={};if(mode==='ALL'||mode==='SHOOTING_ONLY'){const shots={stat:'PLAYER_SHOTS',mean:muShots,dispersion:m.shot_dispersion,at_least:ladder(muShots,m.shot_dispersion,8)};shots.model_hash=await sha256Json(shots);const sot={stat:'PLAYER_SHOTS_ON_TARGET',mean:muSot,p_sot_given_shot:m.p_sot_given_shot,dispersion:m.shot_dispersion,at_least:ladder(muSot,m.shot_dispersion,5)};sot.model_hash=await sha256Json(sot);heads.PLAYER_SHOTS=shots;heads.PLAYER_SHOTS_ON_TARGET=sot;}frozenOutfield.push({player_id:m.player_id,player_name:m.player_name,team_id:teamId,projected_minutes_mean:m.minutes_mean,confidence:m.confidence,fragility:m.fragility,evidence_source_ids:m.evidence_source_ids,quant_input_receipt_sha256:m.quant_input_receipt_sha256,heads});}const unmodelledSot=a.unmodelled*tm.unmodelled_p_sot,sotMean=modeledSot+unmodelledSot;requireThat(sotMean<=tm.shot_mean+1e-9,`team ${teamId} SOT exceeds shots`);teamEnvironment[teamId]={...tm,unmodelled_shot_mean:a.unmodelled,modeled_sot_mean:modeledSot,unmodelled_sot_mean:unmodelledSot,sot_mean:sotMean};}
  const frozenKeepers=[],keeperTeams=new Set();for(const m of goalkeeperModels||[]){const key=playerKey(m),rp=research.get(key);requireThat(rp&&String(rp.player_type).toUpperCase()==='GOALKEEPER',`${key} goalkeeper missing/mismatched research`);requireThat(String(rp.availability_status).toUpperCase()!=='OUT',`cannot model OUT goalkeeper ${key}`);const teamId=String(m.team_id||'');requireThat(teamId===String(rp.team_id)&&teamIds.has(teamId)&&!keeperTeams.has(teamId),`${key} goalkeeper team mismatch/duplicate`);keeperTeams.add(teamId);const opponent=[...teamIds].find(x=>x!==teamId),pSave=probability(m.p_save_given_sot,`${key}.p_save_given_sot`),disp=positive(m.save_dispersion,`${key}.save_dispersion`),confidence=String(m.confidence||'').toUpperCase(),fragility=String(m.fragility||'').toUpperCase();requireThat(VALID_CONFIDENCE.has(confidence),`${key}.confidence invalid`);requireThat(VALID_FRAGILITY.has(fragility),`${key}.fragility invalid`);const minutes=Number(rp.projected_minutes.mean),mean=teamEnvironment[opponent].sot_mean*pSave*(minutes/90),heads={};if(mode==='ALL'||mode==='SAVES_ONLY'){const saves={stat:'GOALKEEPER_SAVES',mean,opponent_sot_mean:teamEnvironment[opponent].sot_mean,p_save_given_sot:pSave,dispersion:disp,at_least:ladder(mean,disp,8)};saves.model_hash=await sha256Json(saves);heads.GOALKEEPER_SAVES=saves;}frozenKeepers.push({player_id:String(m.player_id||rp.player_id||''),player_name:String(rp.player_name),team_id:teamId,projected_minutes_mean:minutes,confidence,fragility,evidence_source_ids:sourceIds(m.evidence_source_ids,known,`${key}.evidence_source_ids`),quant_input_receipt_sha256:receipt(m.quant_input_receipt_sha256,`${key}.quant_input_receipt_sha256`),heads});}
  if(mode==='ALL'||mode==='SAVES_ONLY')requireThat(keeperTeams.size===2,'save freeze requires one goalkeeper per team');
  const researchHash=await sha256Json(researchContext),artifact={schema_version:'aleague_player_volume_freeze_v1',market_data:false,fixture_id:researchContext.fixture_id,pack_revision:researchContext.pack_revision,run_mode:mode,frozen_at:frozenAt||new Date().toISOString(),research_context_sha256:researchHash,team_environment:teamEnvironment,outfield_players:frozenOutfield,goalkeepers:frozenKeepers};artifact.freeze_hash=await sha256Json(artifact);return artifact;
}
