import test from 'node:test';
import assert from 'node:assert/strict';
import {buildFrozenFixture,marketKeyHits,validateResearchContext} from './freeze_core.js';
import {AleaguePlayerVolumeRun} from './run.js';

const H='a'.repeat(64);
const source={s1:{title:'Official team report',url:'https://example.com/source',checked_at:'2026-10-01T00:00:00Z'}};
function player(id,name,team,type,role){return {player_id:id,player_name:name,team_id:team,player_type:type,availability_status:'ACTIVE',availability_source_ids:['s1'],projected_minutes:{low:type==='GOALKEEPER'?90:65,mean:type==='GOALKEEPER'?90:78,high:90,source_ids:['s1']},role:{state:'RETURNING_SAME',position_role:role,source_ids:['s1'],notes:['Current role independently checked']},stat_context:type==='GOALKEEPER'?{saves:{source_ids:['s1'],notes:['Historical save context reviewed']}}:{shots:{source_ids:['s1'],notes:['Shot volume reviewed']},shots_on_target:{source_ids:['s1'],notes:['SOT conversion reviewed']}}};}
function research(){return {schema_version:'aleague_player_volume_research_v1',market_data:false,run_mode:'ALL',fixture_id:'fixture-1',pack_revision:'pack-1',checked_at:'2026-10-01T01:00:00Z',sources:source,fixture_context:{home_team_id:'home',away_team_id:'away',kickoff_utc:'2026-10-02T08:00:00Z',status:'SCHEDULED',source_ids:['s1']},teams:[{team_id:'home',team_name:'Home',source_ids:['s1'],notes:['Team attack researched']},{team_id:'away',team_name:'Away',source_ids:['s1'],notes:['Team attack researched']}],players:[player('h1','Home Striker','home','OUTFIELD','CF'),player('hgk','Home Keeper','home','GOALKEEPER','GK'),player('a1','Away Striker','away','OUTFIELD','CF'),player('agk','Away Keeper','away','GOALKEEPER','GK')]};}
function teamModels(){return ['home','away'].map((team,i)=>({team_id:team,shot_mean:12+i,shot_dispersion:5,unmodelled_weight:4,unmodelled_p_sot:0.31,evidence_source_ids:['s1'],quant_input_receipt_sha256:H}));}
function outfieldModels(){return [{player_id:'h1',team_id:'home',shots_per90_prior:3.2,role_multiplier:1.05,p_sot_given_shot:0.42,shot_dispersion:3,confidence:'A',fragility:'LOW',evidence_source_ids:['s1'],quant_input_receipt_sha256:H},{player_id:'a1',team_id:'away',shots_per90_prior:2.8,role_multiplier:1,p_sot_given_shot:0.38,shot_dispersion:3.5,confidence:'B',fragility:'MEDIUM',evidence_source_ids:['s1'],quant_input_receipt_sha256:H}];}
function keeperModels(){return [{player_id:'hgk',team_id:'home',p_save_given_sot:0.71,save_dispersion:4,confidence:'A',fragility:'LOW',evidence_source_ids:['s1'],quant_input_receipt_sha256:H},{player_id:'agk',team_id:'away',p_save_given_sot:0.69,save_dispersion:4,confidence:'B',fragility:'LOW',evidence_source_ids:['s1'],quant_input_receipt_sha256:H}];}

test('research contract rejects market leakage recursively',()=>{const r=research();r.players[0].role.odds=2.1;assert.ok(marketKeyHits(r).length===1);assert.throws(()=>validateResearchContext(r),/market-derived/);});

test('freeze is coherent and hash-addressed',async()=>{const frozen=await buildFrozenFixture(research(),teamModels(),outfieldModels(),keeperModels(),{frozenAt:'2026-10-01T02:00:00Z'});assert.equal(frozen.market_data,false);assert.match(frozen.freeze_hash,/^[0-9a-f]{64}$/);assert.equal(frozen.outfield_players.length,2);assert.equal(frozen.goalkeepers.length,2);for(const row of frozen.outfield_players){assert.match(row.heads.PLAYER_SHOTS.model_hash,/^[0-9a-f]{64}$/);assert.ok(row.heads.PLAYER_SHOTS.mean>=row.heads.PLAYER_SHOTS_ON_TARGET.mean);}for(const row of frozen.goalkeepers)assert.ok(row.heads.GOALKEEPER_SAVES.mean>=0);});

class MemoryStorage{constructor(){this.map=new Map();}async get(k){return this.map.get(k);}async put(key,value){if(typeof key==='string')this.map.set(key,value);else for(const [k,v] of Object.entries(key))this.map.set(k,v);}}
function req(path,method='GET',body=null){return new Request(`https://run.local${path}`,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});}

test('durable run emits canonical receipt and cannot mutate after freeze',async()=>{const storage=new MemoryStorage(),run=new AleaguePlayerVolumeRun({storage},{}),lock={run_id:'b'.repeat(64),fixture_id:'fixture-1',run_mode:'ALL',source_commit:'c'.repeat(40),pack_revision:'pack-1',qbase_revision:'q-1',advanced_revision:'adv-1',created_at:'2026-10-01T00:00:00Z'};let res=await run.handle(req('/init','POST',{lock}));assert.equal(res.status,201);res=await run.handle(req('/research','POST',{research:research()}));assert.equal((await res.json()).status,'RESEARCH_COMPLETE');res=await run.handle(req('/freeze','POST',{team_models:teamModels(),outfield_models:outfieldModels(),goalkeeper_models:keeperModels()}));const payload=await res.json();assert.equal(payload.status,'FROZEN');assert.match(payload.freeze_receipt_sha256,/^[0-9a-f]{64}$/);assert.equal(payload.frozen.freeze_receipt_sha256,payload.freeze_receipt_sha256);assert.equal(payload.frozen.model_version,'ALEAGUE_PLAYER_VOLUME_V1_0.3.0');assert.ok(!('freeze_hash' in payload.frozen));assert.ok(!('research_context_sha256' in payload.frozen));assert.match(payload.frozen.research_hash,/^[0-9a-f]{64}$/);await assert.rejects(()=>run.handle(req('/research','POST',{research:research()})),/Run already frozen/);await assert.rejects(()=>run.handle(req('/freeze','POST',{team_models:teamModels(),outfield_models:outfieldModels(),goalkeeper_models:keeperModels()})),/Research must be complete/);});
