import test from 'node:test';
import assert from 'node:assert/strict';
import {AleaguePlayerVolumeRun} from './run.js';

const H='d'.repeat(64),RUN='e'.repeat(64);
const source={s1:{title:'Official source',url:'https://example.com/source',checked_at:'2026-10-01T00:00:00Z'}};
function participant(id,name,team,type,role){return {player_id:id,player_name:name,team_id:team,player_type:type,availability_status:'ACTIVE',availability_source_ids:['s1'],projected_minutes:{low:type==='GOALKEEPER'?90:60,mean:type==='GOALKEEPER'?90:78,high:90,source_ids:['s1']},role:{state:'RETURNING_SAME',position_role:role,source_ids:['s1'],notes:['Role checked']},stat_context:type==='GOALKEEPER'?{saves:{source_ids:['s1'],notes:['Saves checked']}}:{shots:{source_ids:['s1'],notes:['Shots checked']},shots_on_target:{source_ids:['s1'],notes:['SOT checked']}}};}
function research(){return {schema_version:'aleague_player_volume_research_v1',market_data:false,run_mode:'ALL',fixture_id:'fixture-1',pack_revision:'pack-1',checked_at:'2026-10-01T01:00:00Z',sources:source,fixture_context:{home_team_id:'H',away_team_id:'A',kickoff_utc:'2026-10-02T08:00:00Z',status:'SCHEDULED',source_ids:['s1']},teams:[{team_id:'H',team_name:'Home',source_ids:['s1'],notes:['Team checked']},{team_id:'A',team_name:'Away',source_ids:['s1'],notes:['Team checked']}],players:[participant('h1','Home Forward','H','OUTFIELD','CF'),participant('hg','Home Keeper','H','GOALKEEPER','GK'),participant('a1','Away Forward','A','OUTFIELD','CF'),participant('ag','Away Keeper','A','GOALKEEPER','GK')]};}
const teamModels=()=>[{team_id:'H',shot_mean:12,shot_dispersion:5,unmodelled_weight:4,unmodelled_p_sot:0.31,evidence_source_ids:['s1'],quant_input_receipt_sha256:H},{team_id:'A',shot_mean:13,shot_dispersion:5,unmodelled_weight:4,unmodelled_p_sot:0.31,evidence_source_ids:['s1'],quant_input_receipt_sha256:H}];
const outfieldModels=()=>[{player_id:'h1',team_id:'H',shots_per90_prior:3.2,role_multiplier:1.05,p_sot_given_shot:0.42,shot_dispersion:3,confidence:'A',fragility:'LOW',evidence_source_ids:['s1'],quant_input_receipt_sha256:H},{player_id:'a1',team_id:'A',shots_per90_prior:2.8,role_multiplier:1,p_sot_given_shot:0.38,shot_dispersion:3.5,confidence:'B',fragility:'MEDIUM',evidence_source_ids:['s1'],quant_input_receipt_sha256:H}];
const keeperModels=()=>[{player_id:'hg',team_id:'H',p_save_given_sot:0.71,save_dispersion:4,confidence:'A',fragility:'LOW',evidence_source_ids:['s1'],quant_input_receipt_sha256:H},{player_id:'ag',team_id:'A',p_save_given_sot:0.69,save_dispersion:4,confidence:'B',fragility:'LOW',evidence_source_ids:['s1'],quant_input_receipt_sha256:H}];
class Storage{constructor(){this.m=new Map();}async get(k){return this.m.get(k);}async put(k,v){if(typeof k==='string')this.m.set(k,v);else Object.entries(k).forEach(([a,b])=>this.m.set(a,b));}}
const req=(path,method='GET',body=null)=>new Request(`https://run.local${path}`,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
async function frozenRun(){const storage=new Storage(),run=new AleaguePlayerVolumeRun({storage},{}),lock={run_id:RUN,fixture_id:'fixture-1',run_mode:'ALL',source_commit:'f'.repeat(40),pack_revision:'pack-1',qbase_revision:'q-1',advanced_revision:'adv-1',created_at:'2026-10-01T00:00:00Z'};await run.handle(req('/init','POST',{lock}));await run.handle(req('/research','POST',{research:research()}));const freezeRes=await run.handle(req('/freeze','POST',{team_models:teamModels(),outfield_models:outfieldModels(),goalkeeper_models:keeperModels()}));return {storage,run,freeze:await freezeRes.json()};}

test('freeze persists exact quantitative input receipt',async()=>{const {run,freeze}=await frozenRun();assert.match(freeze.model_input_receipt_sha256,/^[0-9a-f]{64}$/);const res=await run.handle(req('/model-inputs')),payload=await res.json();assert.equal(payload.status,'FROZEN');assert.equal(payload.model_input_receipt_sha256,freeze.model_input_receipt_sha256);assert.equal(payload.model_inputs.research_hash,freeze.frozen.research_hash);assert.equal(payload.model_inputs.team_models.length,2);assert.equal(payload.model_inputs.outfield_models.length,2);assert.equal(payload.model_inputs.goalkeeper_models.length,2);assert.equal(payload.model_inputs.market_data,false);});

test('tampered stored model inputs fail receipt verification',async()=>{const {storage,run}=await frozenRun();const inputs=structuredClone(await storage.get('model_inputs'));inputs.team_models[0].shot_mean=99;await storage.put('model_inputs',inputs);await assert.rejects(()=>run.handle(req('/model-inputs')),/receipt mismatch/);});

test('model inputs cannot be fetched before freeze',async()=>{const storage=new Storage(),run=new AleaguePlayerVolumeRun({storage},{}),lock={run_id:RUN,fixture_id:'fixture-1',run_mode:'ALL',source_commit:'f'.repeat(40),pack_revision:'pack-1',qbase_revision:'q-1',advanced_revision:'adv-1',created_at:'2026-10-01T00:00:00Z'};await run.handle(req('/init','POST',{lock}));await assert.rejects(()=>run.handle(req('/model-inputs')),/only after freeze/);});
