from pathlib import Path

root = Path('nbl_player_props_v1/worker')

# 1) Remove the runtime unauthenticated GitHub commits API lookup and bind
# runtime assets to the exact commit supplied by the Workers Build instead.
p = root / 'freeze_run.js'
s = p.read_text()
old = "import {computeFreeze,marketKeyHits,requireThat,sha256Json,validateResearchContext} from './freeze_core.js';\n\nconst GH_API='https://api.github.com/repos/Nstp651/nfl_free_research_pack_v1/commits/main';\n"
new = "import {computeFreeze,marketKeyHits,requireThat,sha256Json,validateResearchContext} from './freeze_core.js';\nimport {DEPLOY_SOURCE_COMMIT} from './source_commit.generated.js';\n\n"
assert old in s, 'freeze_run import/GH_API anchor not found'
s = s.replace(old, new, 1)
old = "  return url===GH_API ||\n    /^https:\\/\\/raw\\.githubusercontent\\.com\\/Nstp651\\/nfl_free_research_pack_v1\\/[a-f0-9]{40}\\/nbl_player_props_v1\\/data\\/[A-Za-z0-9_./-]+\\.json$/.test(url) ||\n"
new = "  return /^https:\\/\\/raw\\.githubusercontent\\.com\\/Nstp651\\/nfl_free_research_pack_v1\\/[a-f0-9]{40}\\/nbl_player_props_v1\\/data\\/[A-Za-z0-9_./-]+\\.json$/.test(url) ||\n"
assert old in s, 'allowedUrl GH_API anchor not found'
s = s.replace(old, new, 1)
old = "async function loadAssets(){\n  const head=await readJson(GH_API,{maxBytes:100_000});requireThat(/^[a-f0-9]{40}$/.test(String(head.sha||'')),'Invalid GitHub source commit');\n  const commit=head.sha,manifest=await readJson(rawUrl(commit,'manifest.json'),{maxBytes:200_000});\n"
new = "async function loadAssets(){\n  const commit=String(DEPLOY_SOURCE_COMMIT||'').trim();requireThat(/^[a-f0-9]{40}$/.test(commit)&&!/^0{40}$/.test(commit),'Invalid build-pinned source commit');\n  const manifest=await readJson(rawUrl(commit,'manifest.json'),{maxBytes:200_000});\n"
assert old in s, 'loadAssets GH_API anchor not found'
s = s.replace(old, new, 1)
p.write_text(s)

# 2) Generate the source commit module at build time. The checked-in placeholder
# intentionally fails closed if a deployment ever skips the custom build step.
(root / 'source_commit.generated.js').write_text(
    "// Build-generated. Placeholder intentionally fails closed if Wrangler custom build does not run.\n"
    "export const DEPLOY_SOURCE_COMMIT='0000000000000000000000000000000000000000';\n"
)
(root / 'build_source_commit.mjs').write_text("""import {execFileSync} from 'node:child_process';
import {writeFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';

let sha=String(process.env.WORKERS_CI_COMMIT_SHA||'').trim().toLowerCase();
if(!sha){
  sha=execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8',cwd:fileURLToPath(new URL('../../',import.meta.url))}).trim().toLowerCase();
}
if(!/^[0-9a-f]{40}$/.test(sha))throw new Error('Unable to resolve exact 40-character deployment source commit');
const target=fileURLToPath(new URL('./source_commit.generated.js',import.meta.url));
writeFileSync(target,`// Generated by build_source_commit.mjs; do not hand edit.\\nexport const DEPLOY_SOURCE_COMMIT='${sha}';\\n`);
console.log(`NBL_DEPLOY_SOURCE_COMMIT=${sha}`);
""")

# 3) Ensure Wrangler runs the source-commit generator before bundling.
w = root / 'wrangler.toml'
ws = w.read_text().rstrip() + '\n'
assert '[build]' not in ws, 'Research wrangler already has a build section; inspect before patching'
ws += '\n[build]\ncommand = "node build_source_commit.mjs"\n'
w.write_text(ws)

# 4) Regression test: generate the local commit before importing the Worker and
# prove the immutable run lock records that exact deployed source commit.
t = root / 'freeze_run_entry.test.mjs'
ts = t.read_text()
old = "import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport {NblMatchRun} from './freeze_run_entry.js';\nimport {sha256Json} from './freeze_core.js';\n"
new = "import test from 'node:test';\nimport assert from 'node:assert/strict';\nimport {execFileSync} from 'node:child_process';\nimport {fileURLToPath} from 'node:url';\nimport {sha256Json} from './freeze_core.js';\n\nexecFileSync(process.execPath,[fileURLToPath(new URL('./build_source_commit.mjs',import.meta.url))],{stdio:'inherit'});\nconst {DEPLOY_SOURCE_COMMIT}=await import('./source_commit.generated.js');\nconst {NblMatchRun}=await import('./freeze_run_entry.js');\n"
assert old in ts, 'test import anchor not found'
ts = ts.replace(old, new, 1)
old = "let res=await req(run,'POST','',{fixture_id:'fixture-1',season_start:2026,run_mode:'BOTH'});assert.equal(res.status,200);let d=await res.json();assert.equal(d.status,'RESEARCH_PENDING');assert.equal(d.lock.asset_revision,h.manifest.asset_revision);"
new = "let res=await req(run,'POST','',{fixture_id:'fixture-1',season_start:2026,run_mode:'BOTH'});assert.equal(res.status,200);let d=await res.json();assert.equal(d.status,'RESEARCH_PENDING');assert.equal(d.lock.asset_revision,h.manifest.asset_revision);assert.equal(d.lock.source_commit,DEPLOY_SOURCE_COMMIT);"
assert old in ts, 'test source_commit assertion anchor not found'
ts = ts.replace(old, new, 1)
t.write_text(ts)
