import test from 'node:test';
import assert from 'node:assert/strict';
import marketWorker from './index.js';
import {evaluateMarkets,normalizeRows,validateFrozenFixture} from './evaluate.js';
import {AleaguePlayerVolumeRun} from '../worker/run.js';

const H='a'.repeat(64),RUN='b'.repeat(64);
const source={s1:{title:'Official report',url:'https://example.com/source',checked_at:'2026-10-01T00:00:00Z'}};
function player(id,name,team,type,role){return {player_id:id,player_name:name,team_id:team,player_type:type,availability_status:'ACTIVE',availability_source_ids:['s1'],projected_minutes:{low:type==='GOALKEEPER'?90:65,mean:type==='GOALKEEPER'?90:78,high:90,source_ids:['s1']},role:{state:'RETURNING_SAME',position_role:role,source_ids:['s1'],notes:['Role checked']},stat_context:type==='GOALKEEPER'?{saves:{source_ids:['s1'],notes:['Save history checked']}}:{shots:{source_ids:['s1'],notes:['Shots checked']},shots_on_target:{source_ids:['s1'],notes:['SOT checked']}}};}
function research(){return {schema_version:'aleague_player_volume_research_v1',market_data:false,run_mode:'ALL',fixture_id:'fixture-1',pack_revision:'pack-1',checked_at:'2026-10-01T01:00:00Z',sources:source,fixture_context:{home_team_id:'home',away_team_id:'away',kickoff_utc:'2026-10-02T08:00:00Z',status:'SCHEDULED',source_ids:['s1']},teams:[{team_id:'home',team_name:'Home',source_ids:['s1'],notes:['Attack checked']},{team_id:'away',team_name:'Away',source_ids:['s1'],notes:['Attack checked']}],players:[player('h1','Home Striker','home','OUTFIELD','CF'),player('hgk','Home Keeper','home','GOALKEEPER','GK'),player('a1','Away Striker','away','OUTFIELD','CF'),player('agk','Away Keeper','away','GOALKEEPER','GK')]};}
const teamModels=()=>['home','away'].map((team,i)=>({team_id:team,shot_mean:12+i,shot_dispersion:5,unmodelled_weight:4,unmodelled_p_sot:0.31,evidence_source_ids:['s1'],quant_input_receipt_sha256:H}));
const outfieldModels=()=>[{player_id:'h1',team_id:'home',shots_per90_prior:3.2,role_multiplier:1.05,p_sot_given_shot:0.42,shot_dispersion:3,confidence:'A',fragility:'LOW',evidence_source_ids:['s1'],quant_input_receipt_sha256:H},{player_id:'a1',team_id:'away',shots_per90_prior:2.8,role_multiplier:1,p_sot_given_shot:0.38,shot_dispersion:3.5,confidence:'B',fragility:'MEDIUM',evidence_source_ids:['s1'],quant_input_receipt_sha256:H}];
const keeperModels=()=>[{player_id:'hgk',team_id:'home',p_save_given_sot:0.71,save_dispersion:4,confidence:'A',fragility:'LOW',evidence_source_ids:['s1'],quant_input_receipt_sha256:H},{player_id:'agk',team_id:'away',p_save_given_sot:0.69,save_dispersion:4,confidence:'B',fragility:'LOW',evidence_source_ids:['s1'],quant_input_receipt_sha256:H}];
class Storage{constructor(){this.m=new Map();}async get(k){return this.m.get(k);}async put(k,v){if(typeof k==='string')this.m.set(k,v);else Object.entries(k).forEach(([a,b])=>this.m.set(a,b));}}
const req=(path,method='GET',body=null)=>new Request(`https://run.local${path}`,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
async function frozenPayload(){const run=new AleaguePlayerVolumeRun({storage:new Storage()},{}),lock={run_id:RUN,fixture_id:'fixture-1',run_mode:'ALL',source_commit:'c'.repeat(40),pack_revision:'pack-1',qbase_revision:'q-1',advanced_revision:'adv-1',created_at:'2026-10-01T00:00:00Z'};await run.handle(req('/init','POST',{lock}));await run.handle(req('/research','POST',{research:research()}));const res=await run.handle(req('/freeze','POST',{team_models:teamModels(),outfield_models:outfieldModels(),goalkeeper_models:keeperModels()}));return res.json();}

test('market evaluator verifies receipt, best price and push partition',async()=>{const payload=await frozenPayload(),rows=normalizeRows('fixture-1',[{player_id:'h1',player_name:'Home Striker',stat_type:'SHOTS',side:'OVER',threshold:2,decimal_price:9,bookmaker:'Book A',captured_at:'2026-10-01T03:00:00Z'},{player_id:'h1',player_name:'Home Striker',stat_type:'PLAYER_SHOTS',side:'OVER',threshold:2,decimal_price:12,bookmaker:'Book B',captured_at:'2026-10-01T03:01:00Z'}],{defaultSourceType:'MANUAL'});const result=await evaluateMarkets(payload.frozen,rows);assert.equal(result.market_records_evaluated,1);assert.equal(result.evaluated[0].bookmaker,'Book B');assert.ok(result.evaluated[0].p_push>0);assert.equal(result.best_single.bookmaker,'Book B');assert.equal(result.best_single.selection_eligible,true);});

test('UNDER can be audited but is not recommended by default',async()=>{const payload=await frozenPayload(),rows=normalizeRows('fixture-1',[{player_id:'h1',player_name:'Home Striker',stat_type:'SOT',side:'UNDER',threshold:4.5,decimal_price:10,bookmaker:'Audit Book',captured_at:'2026-10-01T03:00:00Z'}]);const result=await evaluateMarkets(payload.frozen,rows);assert.equal(result.evaluated[0].selection_eligible,false);assert.equal(result.positive_edges.length,0);assert.equal(result.no_forced_bet,true);});

test('tampered frozen probability is rejected',async()=>{const payload=await frozenPayload(),bad=structuredClone(payload.frozen);bad.outfield_players[0].heads.PLAYER_SHOTS.at_least['2']=0.999;await assert.rejects(()=>validateFrozenFixture(bad),/freeze receipt mismatch/);});

test('market Worker fetches frozen run through service binding only',async()=>{const payload=await frozenPayload();let fetchedUrl=null;const env={RESEARCH_FREEZE:{fetch:async request=>{fetchedUrl=request.url;return new Response(JSON.stringify(payload),{status:200,headers:{'content-type':'application/json'}});}}};const clientBody={run_id:RUN,records:[{player_id:'h1',player_name:'Home Striker',stat_type:'SHOTS',side:'AT_LEAST',threshold:2,decimal_price:10,bookmaker:'Book A',captured_at:'2026-10-01T03:00:00Z'}]};assert.ok(!('frozen' in clientBody));const request=new Request('https://market.example/v1/evaluate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(clientBody)});const res=await marketWorker.fetch(request,env),body=await res.json();assert.equal(res.status,200);assert.equal(fetchedUrl,`https://research.internal/v1/runs/${RUN}/frozen`);assert.equal(body.run_id,RUN);assert.match(body.freeze_receipt_sha256,/^[0-9a-f]{64}$/);});
