const VALID_STATS=new Set(['PLAYER_SHOTS','PLAYER_SHOTS_ON_TARGET','GOALKEEPER_SAVES']);
const VALID_SIDES=new Set(['AT_LEAST','OVER','UNDER']);
const VALID_SOURCES=new Set(['SCREENSHOT','MANUAL','ODDS_API']);
const STAT_ALIASES={PLAYER_SHOTS:'PLAYER_SHOTS',SHOTS:'PLAYER_SHOTS',TOTAL_SHOTS:'PLAYER_SHOTS',PLAYER_SHOTS_ON_TARGET:'PLAYER_SHOTS_ON_TARGET',SHOTS_ON_TARGET:'PLAYER_SHOTS_ON_TARGET',SOT:'PLAYER_SHOTS_ON_TARGET',PLAYER_SOT:'PLAYER_SHOTS_ON_TARGET',GOALKEEPER_SAVES:'GOALKEEPER_SAVES',KEEPER_SAVES:'GOALKEEPER_SAVES',SAVES:'GOALKEEPER_SAVES'};
const SIDE_ALIASES={AT_LEAST:'AT_LEAST',MILESTONE:'AT_LEAST',PLUS:'AT_LEAST','+':'AT_LEAST',OVER:'OVER',UNDER:'UNDER'};
const CONF_RANK={A:0,B:1,C:2},FRAG_RANK={LOW:0,MEDIUM:1,HIGH:2},HASH64=/^[0-9a-f]{64}$/;

function requireThat(condition,message){if(!condition)throw new Error(message);}
function stable(value){if(Array.isArray(value))return value.map(stable);if(value&&typeof value==='object')return Object.fromEntries(Object.keys(value).sort().map(k=>[k,stable(value[k])]));return value;}
async function sha256Json(value){const raw=JSON.stringify(stable(value)),hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(raw));return [...new Uint8Array(hash)].map(x=>x.toString(16).padStart(2,'0')).join('');}
function normName(value){return String(value||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'');}
function canonicalStat(value){const key=String(value||'').trim().toUpperCase().replace(/[ -]+/g,'_'),stat=STAT_ALIASES[key];requireThat(stat,`unsupported stat_type ${value}`);return stat;}
function canonicalSide(value){const side=SIDE_ALIASES[String(value||'').trim().toUpperCase()];requireThat(side,`unsupported side ${value}`);return side;}
function capturedAt(value){const text=String(value||'').trim();requireThat(text&&Number.isFinite(Date.parse(text)),'captured_at must be ISO-8601');requireThat(/[zZ]|[+-]\d\d:\d\d$/.test(text),'captured_at must be timezone-aware');return text;}

export async function validateFrozenFixture(frozen){
  requireThat(frozen&&typeof frozen==='object'&&!Array.isArray(frozen),'frozen artifact must be object');requireThat(frozen.schema_version==='aleague_player_volume_freeze_v1','unexpected freeze schema');requireThat(frozen.model_version==='ALEAGUE_PLAYER_VOLUME_V1_0.3.0','unexpected model version');requireThat(frozen.market_data===false,'frozen artifact must declare market_data=false');const receipt=String(frozen.freeze_receipt_sha256||'');requireThat(HASH64.test(receipt),'freeze receipt missing/invalid');const unsigned=structuredClone(frozen);delete unsigned.freeze_receipt_sha256;requireThat(await sha256Json(unsigned)===receipt,'freeze receipt mismatch');
  const seenIds=new Set(),seenNames=new Set(),players=[...(frozen.outfield_players||[]),...(frozen.goalkeepers||[])];for(const player of players){requireThat(player&&typeof player==='object','invalid frozen player');const id=String(player.player_id||'').trim(),name=normName(player.player_name);if(id){requireThat(!seenIds.has(id),`duplicate frozen player id ${id}`);seenIds.add(id);}requireThat(name&&!seenNames.has(name),`duplicate/empty frozen player name ${name}`);seenNames.add(name);const heads=player.heads||{};requireThat(heads&&typeof heads==='object','invalid frozen heads');for(const [stat,head] of Object.entries(heads)){requireThat(head&&head.stat===stat,`frozen head mismatch ${stat}`);const modelHash=String(head.model_hash||'');requireThat(HASH64.test(modelHash),`${stat} model hash invalid`);const unsignedHead=structuredClone(head);delete unsignedHead.model_hash;requireThat(await sha256Json(unsignedHead)===modelHash,`${stat} model hash mismatch`);const entries=Object.entries(head.at_least||{}).sort((a,b)=>Number(a[0])-Number(b[0]));requireThat(entries.length>0,`${stat} missing at_least ladder`);let previous=1;for(const [key,value] of entries){requireThat(Number.isInteger(Number(key))&&Number(key)>=1,`${stat} threshold key invalid`);const p=Number(value);requireThat(Number.isFinite(p)&&p>=-1e-12&&p<=1+1e-12&&p<=previous+1e-12,`${stat} invalid probability ladder`);previous=p;}}}return frozen;
}

export function normalizeRows(fixtureId,rows,{defaultSourceType='MANUAL',defaultCapturedAt=null}={}){
  const source=String(defaultSourceType||'').trim().toUpperCase();requireThat(VALID_SOURCES.has(source),'unsupported default_source_type');requireThat(Array.isArray(rows),'records must be an array');const timestamp=defaultCapturedAt||new Date().toISOString();return rows.map((row,index)=>{requireThat(row&&typeof row==='object'&&!Array.isArray(row),`records[${index}] must be object`);const stat_type=canonicalStat(row.stat_type),side=canonicalSide(row.side),threshold=Number(row.threshold),decimal_price=Number(row.decimal_price),source_type=String(row.source_type||source).trim().toUpperCase(),bookmaker=String(row.bookmaker||'').trim(),player_name=String(row.player_name||'').trim();requireThat(VALID_STATS.has(stat_type)&&VALID_SIDES.has(side),'market stat/side invalid');requireThat(VALID_SOURCES.has(source_type),'unsupported source_type');requireThat(player_name,'player_name required');requireThat(Number.isFinite(threshold)&&threshold>=0&&threshold<=20&&Math.abs(threshold*2-Math.round(threshold*2))<=1e-9,'threshold must be integer/half-point in range');if(side==='AT_LEAST')requireThat(threshold>=1&&Number.isInteger(threshold),'AT_LEAST threshold must be integer >=1');requireThat(Number.isFinite(decimal_price)&&decimal_price>1&&decimal_price<=1000,'invalid decimal price');requireThat(bookmaker,'bookmaker required');return {fixture_id:String(fixtureId),player_id:row.player_id?String(row.player_id).trim():null,player_name,stat_type,side,threshold,decimal_price,bookmaker,captured_at:capturedAt(row.captured_at||timestamp),source_type};});
}
function bestPrice(records){const map=new Map();for(const row of records){const identity=row.player_id?`id:${row.player_id}`:`name:${row.player_name.toLowerCase()}`,key=[row.fixture_id,identity,row.stat_type,row.side,row.threshold].join('|'),old=map.get(key);if(!old||row.decimal_price>old.decimal_price||(row.decimal_price===old.decimal_price&&`${row.captured_at}|${row.bookmaker.toLowerCase()}`>`${old.captured_at}|${old.bookmaker.toLowerCase()}`))map.set(key,row);}return [...map.values()];}
function playerIndex(frozen){const map=new Map();for(const p of [...(frozen.outfield_players||[]),...(frozen.goalkeepers||[])]){if(String(p.player_id||'').trim())map.set(`id:${String(p.player_id).trim()}`,p);map.set(`name:${normName(p.player_name)}`,p);}return map;}
function atLeast(head,count){if(count<=0)return 1;const value=head.at_least?.[String(Math.trunc(count))];requireThat(value!==undefined,`exact frozen count threshold ${count}+ unavailable`);const p=Number(value);requireThat(p>=0&&p<=1,'frozen probability outside [0,1]');return p;}
function partition(head,side,line){requireThat(Math.abs(line*2-Math.round(line*2))<=1e-9,'only integer/half-point lines supported');if(side==='AT_LEAST'){const p=atLeast(head,Math.round(line));return [p,0,1-p];}if(!Number.isInteger(line)){const p=atLeast(head,Math.floor(line)+1);return side==='OVER'?[p,0,1-p]:[1-p,0,p];}const n=Math.round(line),ge=atLeast(head,n),geNext=atLeast(head,n+1),eq=ge-geNext,below=1-ge;requireThat(Math.min(eq,below,geNext)>=-1e-12,'invalid integer-line partition');return side==='OVER'?[geNext,eq,below]:[below,eq,geNext];}

export async function evaluateMarkets(frozen,records,{selectionSides=['AT_LEAST','OVER']}={}){
  await validateFrozenFixture(frozen);const sides=new Set(selectionSides.map(x=>String(x).toUpperCase()));requireThat(sides.size>0&&[...sides].every(x=>VALID_SIDES.has(x)),'invalid selection_sides');const index=playerIndex(frozen),rows=bestPrice(records),evaluated=[];for(const row of rows){requireThat(row.fixture_id===String(frozen.fixture_id),'market fixture does not match frozen fixture');let player=row.player_id?index.get(`id:${row.player_id}`):null;if(!player)player=index.get(`name:${normName(row.player_name)}`);requireThat(player,`market player ${row.player_name} not in frozen P_model`);const head=player.heads?.[row.stat_type];requireThat(head,`frozen ${row.stat_type} unavailable for ${row.player_name}`);const [pWin,pPush,pLoss]=partition(head,row.side,row.threshold),price=row.decimal_price,ev=pWin*(price-1)-pLoss,nonPush=pWin+pLoss,conditional=nonPush>0?pWin/nonPush:null,breakEven=1/price;evaluated.push({...row,frozen_player_id:player.player_id||null,frozen_player_name:player.player_name,p_win:pWin,p_push:pPush,p_loss:pLoss,conditional_win_probability:conditional,market_break_even_probability:breakEven,probability_edge:conditional===null?null:conditional-breakEven,fair_decimal_price:pWin>0?nonPush/pWin:null,ev_per_unit:ev,positive_ev:ev>0,selection_eligible:sides.has(row.side),confidence:String(player.confidence||'C'),fragility:String(player.fragility||'HIGH'),model_hash:head.model_hash,freeze_receipt_sha256:frozen.freeze_receipt_sha256,frozen_at:frozen.frozen_at});}
  evaluated.sort((a,b)=>b.ev_per_unit-a.ev_per_unit||(CONF_RANK[a.confidence]??99)-(CONF_RANK[b.confidence]??99)||(FRAG_RANK[a.fragility]??99)-(FRAG_RANK[b.fragility]??99)||a.stat_type.localeCompare(b.stat_type)||a.frozen_player_name.localeCompare(b.frozen_player_name)||a.threshold-b.threshold||a.bookmaker.localeCompare(b.bookmaker));const positives=evaluated.filter(r=>r.positive_ev&&r.selection_eligible);positives.forEach((row,i)=>row.positive_edge_rank=i+1);return {fixture_id:frozen.fixture_id,freeze_receipt_sha256:frozen.freeze_receipt_sha256,frozen_at:frozen.frozen_at,selection_sides:[...sides].sort(),market_records_evaluated:evaluated.length,evaluated,positive_edges:positives,best_single:positives[0]||null,no_forced_bet:positives.length===0};
}
