import test from 'node:test';
import assert from 'node:assert/strict';
import { NbaMarketRun } from './index.js';

const H='a'.repeat(64);
class MemoryStorage{constructor(){this.map=new Map();}async get(k){return this.map.get(k);}async put(k,v){this.map.set(k,structuredClone(v));}}
function freeze(){return {schema_version:'nba_slate_freeze_v1',status:'FROZEN',market_data:false,slate_date_et:'2026-10-20',run_mode:'BOTH',eligible_game_ids:['4019999999'],frozen_at:'2026-10-20T12:00:00Z',freeze_receipt_sha256:H,games:[{game_id:'4019999999',fixture:{season:2027,home_team:{id:'2',name:'Boston Celtics'},away_team:{id:'18',name:'New York Knicks'},start_time_utc:'2026-10-21T00:00:00Z'},players:[{player_id:'100',player_name:'Test Guard',team:'Boston Celtics',confidence:'A',fragility:'LOW',heads:{assists:{final_mean:6,probability_grid:{half_point_grid:[{line:5.5,over:.55,push:0,under:.45}],integer_push_grid:[]}},rebounds:{final_mean:5,probability_grid:{half_point_grid:[{line:4.5,over:.52,push:0,under:.48}],integer_push_grid:[]}}}}]}]};}
function grant(){return {schema_version:'nba_market_access_grant_v1',run_id:'run-1',slate_date_et:'2026-10-20',run_mode:'BOTH',frozen_at:'2026-10-20T12:00:00Z',freeze_receipt_sha256:H,allowed_game_ids:['4019999999'],invalidated_game_ids:[]};}
function service({preFreeze=false}={}){return {async fetch(req){const path=new URL(req.url).pathname;if(path.endsWith('/market-access')){if(preFreeze)return new Response(JSON.stringify({error:'P_MODEL_STATUS must be frozen before market access'}),{status:422,headers:{'content-type':'application/json'}});return new Response(JSON.stringify(grant()),{status:200,headers:{'content-type':'application/json'}});}if(path.endsWith('/freeze'))return new Response(JSON.stringify({status:'FROZEN',freeze:freeze(),invalidations:[]}),{status:200,headers:{'content-type':'application/json'}});return new Response('{}',{status:404});}};}

test('pre-freeze research state blocks market worker before any market action',async()=>{const worker=new NbaMarketRun({storage:new MemoryStorage()},{RESEARCH_SERVICE:service({preFreeze:true}),ODDS_API_KEY:'unused'});const res=await worker.fetch(new Request('https://market/rankings?run_id=run-1'));assert.equal(res.status,422);const value=await res.json();assert.match(value.error,/P_MODEL_STATUS must be frozen/);});

test('manual screenshot refresh preserves exact freeze identity and returns ranking',async()=>{const worker=new NbaMarketRun({storage:new MemoryStorage()},{RESEARCH_SERVICE:service(),ODDS_API_KEY:'unused'});const body={source_type:'BET365_SCREENSHOT',captured_at:'2026-10-20T12:05:00Z',evidence_id:'shot-1',freeze_receipt_sha256:H,quotes:[{game_id:'4019999999',player_id:'100',stat_type:'assists',threshold:5.5,decimal_price:2.10,bookmaker:'Bet365'}]};const res=await worker.fetch(new Request('https://market/manual-quotes?run_id=run-1',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}));assert.equal(res.status,200);const value=await res.json();assert.equal(value.freeze_receipt_sha256,H);assert.equal(value.rankings.frozen_at,'2026-10-20T12:00:00Z');assert.equal(value.rankings.best_single.bookmaker,'Bet365');});
