import test from 'node:test';
import assert from 'node:assert/strict';
import { NbaMarketRun } from './index.js';

const H='a'.repeat(64),PH='b'.repeat(64),AH='c'.repeat(64),RH='d'.repeat(64),FROZEN_AT='2026-01-01T00:00:00Z';
class MemoryStorage{constructor(){this.map=new Map();}async get(k){return this.map.get(k);}async put(k,v){this.map.set(k,structuredClone(v));}}
function freeze(){return {schema_version:'nba_slate_freeze_v1',status:'FROZEN',market_data:false,slate_date_et:'2026-10-20',run_mode:'BOTH',eligible_game_ids:['4019999999'],frozen_at:FROZEN_AT,freeze_receipt_sha256:H,games:[{game_id:'4019999999',fixture:{season:2027,home_team:{id:'2',name:'Boston Celtics'},away_team:{id:'18',name:'New York Knicks'},start_time_utc:'2026-10-21T00:00:00Z'},players:[{player_id:'100',player_name:'Test Guard',team:'Boston Celtics',confidence:'A',fragility:'LOW',player_model_sha256:PH,heads:{assists:{final_mean:6,head_model_sha256:AH,probability_grid:{half_point_grid:[{line:5.5,over:.55,push:0,under:.45}],integer_push_grid:[]}},rebounds:{final_mean:5,head_model_sha256:RH,probability_grid:{half_point_grid:[{line:4.5,over:.52,push:0,under:.48}],integer_push_grid:[]}}}}]}]};}
function grant(){return {schema_version:'nba_market_access_grant_v1',run_id:'run-1',slate_date_et:'2026-10-20',run_mode:'BOTH',frozen_at:FROZEN_AT,freeze_receipt_sha256:H,allowed_game_ids:['4019999999'],invalidated_game_ids:[]};}
function service({preFreeze=false}={}){return {async fetch(req){const path=new URL(req.url).pathname;if(path.endsWith('/market-access')){if(preFreeze)return new Response(JSON.stringify({error:'P_MODEL_STATUS must be frozen before market access'}),{status:422,headers:{'content-type':'application/json'}});return new Response(JSON.stringify(grant()),{status:200,headers:{'content-type':'application/json'}});}if(path.endsWith('/freeze'))return new Response(JSON.stringify({status:'FROZEN',freeze:freeze(),invalidations:[]}),{status:200,headers:{'content-type':'application/json'}});return new Response('{}',{status:404});}};}

test('pre-freeze research state blocks market worker before any market action',async()=>{const worker=new NbaMarketRun({storage:new MemoryStorage()},{RESEARCH_SERVICE:service({preFreeze:true}),ODDS_API_KEY:'unused'});const res=await worker.fetch(new Request('https://market/rankings?run_id=run-1'));assert.equal(res.status,422);const value=await res.json();assert.match(value.error,/P_MODEL_STATUS must be frozen/);});

test('manual screenshot refresh preserves exact freeze identity and returns ranking',async()=>{const worker=new NbaMarketRun({storage:new MemoryStorage()},{RESEARCH_SERVICE:service(),ODDS_API_KEY:'unused'});const body={refresh_request_id:'manual-refresh-001',source_type:'BET365_SCREENSHOT',captured_at:'2026-10-20T12:05:00Z',evidence_id:'shot-1',freeze_receipt_sha256:H,quotes:[{game_id:'4019999999',player_id:'100',stat_type:'assists',threshold:5.5,decimal_price:2.10,bookmaker:'Bet365'}]};const res=await worker.fetch(new Request('https://market/manual-quotes?run_id=run-1',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}));assert.equal(res.status,200);const value=await res.json();assert.equal(value.freeze_receipt_sha256,H);assert.equal(value.manual_snapshot.replayed,false);assert.equal(value.rankings.frozen_at,FROZEN_AT);assert.equal(value.rankings.best_single.bookmaker,'Bet365');assert.equal(value.rankings.best_single.player_model_sha256,PH);assert.equal(value.rankings.best_single.head_model_sha256,AH);const retry=await worker.fetch(new Request('https://market/manual-quotes?run_id=run-1',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}));const retryValue=await retry.json();assert.equal(retry.status,200);assert.equal(retryValue.manual_snapshot.replayed,true);});

test('identical API refresh retry replays persisted snapshot without spending another Odds API call',async()=>{const original=globalThis.fetch;let calls=0;globalThis.fetch=async input=>{calls++;const url=new URL(String(input));if(url.pathname.endsWith('/events'))return new Response(JSON.stringify([{id:'event-1',sport_key:'basketball_nba',commence_time:'2026-10-21T00:00:00Z',home_team:'Boston Celtics',away_team:'New York Knicks'}]),{status:200,headers:{'content-type':'application/json'}});if(url.pathname.endsWith('/events/event-1/odds'))return new Response(JSON.stringify({id:'event-1',bookmakers:[{key:'tab',title:'TAB',markets:[{key:'player_assists',last_update:'2026-10-20T12:05:00Z',outcomes:[{name:'Over',description:'Test Guard',point:5.5,price:2.10}]}]}]}),{status:200,headers:{'content-type':'application/json','x-requests-last':'4','x-requests-used':'100','x-requests-remaining':'19900'}});throw new Error(`unexpected URL ${url}`);};try{const worker=new NbaMarketRun({storage:new MemoryStorage()},{RESEARCH_SERVICE:service(),ODDS_API_KEY:'key',ODDS_API_REGIONS:'au'});const body=JSON.stringify({refresh_request_id:'api-refresh-001'});const req=()=>new Request('https://market/refresh?run_id=run-1',{method:'POST',headers:{'content-type':'application/json'},body});const first=await worker.fetch(req());assert.equal(first.status,200);const firstValue=await first.json();assert.equal(firstValue.refresh.replayed,false);assert.equal(calls,2);const retry=await worker.fetch(req());assert.equal(retry.status,200);const retryValue=await retry.json();assert.equal(retryValue.refresh.replayed,true);assert.equal(retryValue.rankings.best_single.bookmaker,'TAB');assert.equal(calls,2);}finally{globalThis.fetch=original;}});
