import test from 'node:test';
import assert from 'node:assert/strict';
import { createMarketRun, marketRefreshReplay, applyApiSnapshot, applyManualSnapshot, rankCurrentMarket, reconcileMarketGrant } from './market_run_core.js';

const H='a'.repeat(64),PH='b'.repeat(64),AH='c'.repeat(64),RH='d'.repeat(64);
function pg(){return {half_point_grid:[{line:5.5,over:.55,push:0,under:.45}],integer_push_grid:[{line:5,over:.50,push:.10,under:.40}]};}
function freeze(){return {schema_version:'nba_slate_freeze_v1',status:'FROZEN',market_data:false,slate_date_et:'2026-10-20',run_mode:'BOTH',eligible_game_ids:['4019999999'],frozen_at:'2026-10-20T12:00:00Z',freeze_receipt_sha256:H,games:[{game_id:'4019999999',fixture:{season:2027,home_team:{id:'2',name:'Boston Celtics'},away_team:{id:'18',name:'New York Knicks'},start_time_utc:'2026-10-21T00:00:00Z'},players:[{player_id:'100',player_name:'Test Guard',team:'Boston Celtics',confidence:'A',fragility:'LOW',player_model_sha256:PH,heads:{assists:{final_mean:6.1,head_model_sha256:AH,probability_grid:pg()},rebounds:{final_mean:5.4,head_model_sha256:RH,probability_grid:pg()}}}]}]};}
function grant(){return {schema_version:'nba_market_access_grant_v1',run_id:'run-1',slate_date_et:'2026-10-20',run_mode:'BOTH',frozen_at:'2026-10-20T12:00:00Z',freeze_receipt_sha256:H,allowed_game_ids:['4019999999'],invalidated_game_ids:[]};}
function api(price=1.95,captured='2026-10-20T12:05:00Z'){return {schema_version:'nba_odds_api_refresh_v1',source:'ODDS_API',captured_at:captured,freeze_receipt_sha256:H,quotes:[{source:'ODDS_API',game_id:'4019999999',player_id:'100',player_name:'Test Guard',stat_type:'assists',side:'over',threshold:5.5,decimal_price:price,bookmaker:'API Book',captured_at:captured}],issues:[]};}

test('market state cannot change immutable freeze identity',async()=>{const f=freeze(),s=await createMarketRun({runId:'run-1',freeze:f,grant:grant()});const bad=freeze();bad.frozen_at='2026-10-20T12:01:00Z';assert.throws(()=>reconcileMarketGrant(s,bad,grant()),/freeze timestamp mismatch|frozen identity drift/);});
test('latest API snapshot replaces stale API prices rather than accumulating them',async()=>{const f=freeze();let s=await createMarketRun({runId:'run-1',freeze:f,grant:grant()});s=await applyApiSnapshot(s,api(2.10),{refreshRequestId:'api-refresh-001'});s=await applyApiSnapshot(s,api(1.90,'2026-10-20T12:10:00Z'),{refreshRequestId:'api-refresh-002'});const r=rankCurrentMarket(s,f);assert.equal(r.all_evaluated.length,1);assert.equal(r.all_evaluated[0].decimal_price,1.90);assert.equal(r.all_evaluated[0].player_model_sha256,PH);assert.equal(r.all_evaluated[0].head_model_sha256,AH);assert.equal(s.api_refresh_history.length,1);assert.equal(s.api_refresh_history[0].refresh_request_id,'api-refresh-001');});
test('current API refresh request is replayable but superseded request id is rejected',async()=>{const f=freeze();let s=await createMarketRun({runId:'run-1',freeze:f,grant:grant()});s=await applyApiSnapshot(s,api(2.10),{refreshRequestId:'api-refresh-001'});assert.equal(marketRefreshReplay(s,'api','api-refresh-001').snapshot.snapshot_sha256,s.current_api_snapshot.snapshot_sha256);s=await applyApiSnapshot(s,api(1.90,'2026-10-20T12:10:00Z'),{refreshRequestId:'api-refresh-002'});assert.throws(()=>marketRefreshReplay(s,'api','api-refresh-001'),/superseded snapshot/);});
test('manual screenshot snapshot can beat duplicate API price without changing P_model',async()=>{const f=freeze();let s=await createMarketRun({runId:'run-1',freeze:f,grant:grant()});s=await applyApiSnapshot(s,api(1.95),{refreshRequestId:'api-refresh-001'});s=await applyManualSnapshot(s,f,{refresh_request_id:'manual-refresh-001',source_type:'BET365_SCREENSHOT',captured_at:'2026-10-20T12:06:00Z',evidence_id:'shot-1',freeze_receipt_sha256:H,quotes:[{game_id:'4019999999',player_name:'Test Guard',stat_type:'assists',threshold:5.5,decimal_price:2.20,bookmaker:'Bet365'}]});const r=rankCurrentMarket(s,f);assert.equal(r.decision,'BEST_SINGLE');assert.equal(r.best_single.bookmaker,'Bet365');assert.equal(r.best_single.decimal_price,2.20);assert.equal(r.best_single.player_model_sha256,PH);assert.equal(r.best_single.head_model_sha256,AH);assert.equal(r.freeze_receipt_sha256,H);assert.equal(r.frozen_at,'2026-10-20T12:00:00Z');assert.equal(marketRefreshReplay(s,'manual','manual-refresh-001').snapshot.evidence_id,'shot-1');});
test('manual screenshot captured before freeze is rejected',async()=>{const f=freeze();let s=await createMarketRun({runId:'run-1',freeze:f,grant:grant()});await assert.rejects(()=>applyManualSnapshot(s,f,{refresh_request_id:'manual-refresh-old',source_type:'BET365_SCREENSHOT',captured_at:'2026-10-20T11:59:59Z',evidence_id:'old-shot',freeze_receipt_sha256:H,quotes:[{game_id:'4019999999',player_id:'100',stat_type:'assists',threshold:5.5,decimal_price:2.20,bookmaker:'Bet365'}]}),/predates frozen/);});
test('manual quote cannot submit an unfrozen threshold by interpolation',async()=>{const f=freeze();let s=await createMarketRun({runId:'run-1',freeze:f,grant:grant()});s=await applyManualSnapshot(s,f,{refresh_request_id:'manual-refresh-002',source_type:'BET365_SCREENSHOT',captured_at:'2026-10-20T12:06:00Z',evidence_id:'shot-2',freeze_receipt_sha256:H,quotes:[{game_id:'4019999999',player_id:'100',stat_type:'assists',threshold:6.5,decimal_price:2.20,bookmaker:'Bet365'}]});const r=rankCurrentMarket(s,f);assert.equal(r.all_evaluated.length,0);assert.equal(r.issues.some(x=>x.type==='MARKET_BINDING_OR_THRESHOLD_REJECTED'),true);});
