"""Pin the existing calibrated residuals and Python model hash into the Worker."""
import hashlib
import json
from pathlib import Path
root = Path(__file__).resolve().parents[1]
m = json.loads((root / 'model/qbase_v0.1.0.json').read_text())
h = hashlib.sha256(json.dumps(m, sort_keys=True, separators=(',', ':')).encode()).hexdigest()
bundle = {'model_sha256': h, 'model_version': m['model_version'],
          'residuals': m['walk_forward']['residual_distribution']}
(root / 'worker/residual_bundle.js').write_text('// Generated by tools/build_residual_bundle.py; do not hand-edit.\nexport default ' + json.dumps(bundle, sort_keys=True, separators=(',', ':')) + ';\n')
