import legacy,{evaluate} from './index.js';

const ODDS_HOST='https://api.the-odds-api.com';
const ODDS_SPORT='basketball_nbl';
const DEFAULT_ODDS_MARKETS=['player_assists','player_rebounds','player_assists_alternate','player_rebounds_alternate'];
const ALLOWED_ODDS_MARKETS=new Set(DEFAULT_ODDS_MARKETS);
const MAX_MARKETS=250;
const KICKOFF_TOLERANCE_MS=30*60*1000;
const response=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'content-type':'application/json','cache-control':'no-store','access-control-allow-origin':'*'}});
const need=(c,m)=>{if(!c)throw new Error(m);};
const hash64=x=>/^[0-9a-f]{64}$/.test(String(x||''));
const finite=x=>Number.isFinite(Number(x));
const norm=x=>String(x||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'');
const researchBase=env=>String(env?.RESEARCH_BASE||'https://nbl-player-props-research-v1.nickarnott01.workers.dev').replace(/\/+$/,'');
const oddsIso=ms=>new Date(ms).toISOString().replace(/\.\d{3}Z$/,'Z');

async function readJson(res,label){const text=await res.text();let body;try{body=JSON.parse(text);}catch{throw new Error(`${label} invalid JSON (${res.status})`);}return body;}
async function researchJson(path,env){const url=`${researchBase(env)}${path}`,init={headers:{accept:'application/json','user-agent':'nbl-market-v1/1.3.1'},signal:AbortSignal.timeout(15_000)};const res=env?.RESEARCH&&typeof env.RESEARCH.fetch==='function'?await env.RESEARCH.fetch(new Request(url,init)):await fetch(url,init),body=await readJson(res,'Research response');need(res.ok,`Research Worker ${res.status}: ${body?.error||'request failed'}`);return body;}
function quota(res){return {requests_remaining:res.headers.get('x-requests-remaining'),requests_used:res.headers.get('x-requests-used'),requests_last:res.headers.get('x-requests-last')};}
function providerProblem(res,body,label){return {label,http_status:res.status,error_code:String(body?.error_code||body?.code||'UNKNOWN'),message:String(body?.message||body?.error||'request failed'),quota:quota(res)};}
async function oddsCall(url,label){const res=await fetch(url,{headers:{accept:'application/json','user-agent':'nbl-market-v1/1.3.1'},signal:AbortSignal.timeout(15_000),cf:{cacheTtl:25,cacheEverything:true}}),body=await readJson(res,label);return {res,body,quota:quota(res)};}
function fixtureWindow(fixture){const tip=Date.parse(String(fixture?.start_time||''));need(Number.isFinite(tip),'Frozen fixture start_time invalid');return {from:oddsIso(tip-24*60*60*1000),to:oddsIso(tip+24*60*60*1000)};}
function eventOrientation(event,fixture){const h=norm(fixture?.home_team?.name),a=norm(fixture?.away_team?.name),eh=norm(event?.home_team),ea=norm(event?.away_team);if(eh===h&&ea===a)return'exact';if(eh===a&&ea===h)return'swapped';return'none';}
function resolveEvent(events,fixture){const tip=Date.parse(String(fixture?.start_time||''));const matches=(Array.isArray(events)?events:[]).filter(e=>eventOrientation(e,fixture)!=='none'&&Number.isFinite(Date.parse(String(e?.commence_time||'')))&&Math.abs(Date.parse(e.commence_time)-tip)<=KICKOFF_TOLERANCE_MS);if(matches.length!==1)return null;return matches[0];}
function nearby(events,fixture){const tip=Date.parse(String(fixture?.start_time||''));return (Array.isArray(events)?events:[]).map(e=>({event_id:String(e?.id||''),home_team:String(e?.home_team||''),away_team:String(e?.away_team||''),commence_time:String(e?.commence_time||''),team_orientation:eventOrientation(e,fixture),kickoff_delta_minutes:Number.isFinite(Date.parse(String(e?.commence_time||'')))?Math.round((Date.parse(e.commence_time)-tip)/60000):null})).filter(x=>x.kickoff_delta_minutes!==null&&Math.abs(x.kickoff_delta_minutes)<=1440).slice(0,12);}

export async function fetchEventsDiscovery(env,fixture,{featured=false}={}){
  need(env?.ODDS_API_KEY,'ODDS_API_KEY is not configured');const w=fixtureWindow(fixture),baseParams=featured?{apiKey:env.ODDS_API_KEY,regions:'au',markets:'h2h',oddsFormat:'decimal',dateFormat:'iso'}:{apiKey:env.ODDS_API_KEY,dateFormat:'iso'},path=featured?`/v4/sports/${ODDS_SPORT}/odds`:`/v4/sports/${ODDS_SPORT}/events`;
  const filtered=new URLSearchParams({...baseParams,commenceTimeFrom:w.from,commenceTimeTo:w.to}),first=await oddsCall(`${ODDS_HOST}${path}?${filtered}`,featured?'Odds featured filtered':'Odds events filtered'),attempts=[];if(first.res.ok&&Array.isArray(first.body))return {ok:true,body:first.body,quota:first.quota,mode:'windowed',attempts};attempts.push(providerProblem(first.res,first.body,featured?'featured_windowed':'events_windowed'));
  const plain=new URLSearchParams(baseParams),retry=await oddsCall(`${ODDS_HOST}${path}?${plain}`,featured?'Odds featured unfiltered retry':'Odds events unfiltered retry');if(retry.res.ok&&Array.isArray(retry.body))return {ok:true,body:retry.body,quota:retry.quota,mode:'unfiltered_retry',attempts};attempts.push(providerProblem(retry.res,retry.body,featured?'featured_unfiltered':'events_unfiltered'));return {ok:false,body:[],quota:retry.quota,mode:'failed',attempts};
}

async function loadFrozen(input,env){const runId=String(input.run_id||''),receipt=String(input.expected_freeze_receipt_sha256||'');need(hash64(runId),'run_id invalid');need(hash64(receipt),'expected_freeze_receipt_sha256 required');const run=await researchJson(`/v1/match-runs/${runId}`,env);need(run.status==='FROZEN'&&run.freeze?.status==='FROZEN','P_MODEL_STATUS must be FROZEN before market evaluation');need(run.freeze.freeze_receipt_sha256===receipt,'Freeze receipt mismatch');return {runId,receipt,run,freeze:run.freeze,fixture:run.lock?.fixture||run.freeze.fixture};}
function requestedMarkets(input){const raw=input.markets===undefined?DEFAULT_ODDS_MARKETS:input.markets;need(Array.isArray(raw)&&raw.length>0&&raw.length<=4,'Odds API markets must contain 1-4 supported keys');const out=[...new Set(raw.map(String))];for(const k of out)need(ALLOWED_ODDS_MARKETS.has(k),`Unsupported Odds API market ${k}`);return out;}
async function eventOdds(env,event,markets){const q=new URLSearchParams({apiKey:env.ODDS_API_KEY,regions:'au',markets:markets.join(','),oddsFormat:'decimal',dateFormat:'iso'});return oddsCall(`${ODDS_HOST}/v4/sports/${ODDS_SPORT}/events/${encodeURIComponent(event.id)}/odds?${q}`,'Odds props');}
function statFor(key){if(key==='player_assists'||key==='player_assists_alternate')return'assists';if(key==='player_rebounds'||key==='player_rebounds_alternate')return'rebounds';return null;}
function normalizeRows(raw,event,fixtureId,capturedAt){need(raw&&String(raw.id||'')===String(event.id),'Odds event response identity mismatch');const rows=[];for(const book of Array.isArray(raw.bookmakers)?raw.bookmakers:[]){for(const market of Array.isArray(book.markets)?book.markets:[]){const stat=statFor(String(market?.key||''));if(!stat)continue;for(const o of Array.isArray(market.outcomes)?market.outcomes:[]){const side=String(o?.name||'').toLowerCase(),point=Number(o?.point),price=Number(o?.price);if(!['over','under'].includes(side)||typeof o?.description!=='string'||!finite(point)||!finite(price)||price<=1||point<0||point>40||Math.abs(point*2-Math.round(point*2))>1e-9)continue;rows.push({fixture_id:String(fixtureId),player_id:null,player_name:String(o.description).trim(),stat_type:stat,side,threshold:point,decimal_price:price,bookmaker:String(book.title||book.key||'Unknown'),captured_at:capturedAt,source_type:'odds_api'});}}}const best=new Map();for(const row of rows){const k=[norm(row.player_name),row.stat_type,row.side,row.threshold].join('|'),old=best.get(k);if(!old||row.decimal_price>old.decimal_price)best.set(k,row);}return [...best.values()];}
function code(body){return String(body?.error_code||body?.code||'').toUpperCase();}

export async function fetchAndEvaluateOddsApiV130(input,env){
  const state=await loadFrozen(input,env),requested=requestedMarkets(input);if(!env?.ODDS_API_KEY)return {market_data:true,p_model_mutated:false,p_model_status:'FROZEN',run_id:state.runId,fixture_id:state.freeze.fixture_id,freeze_receipt_sha256:state.receipt,frozen_at:state.freeze.frozen_at,odds_api_support:'NOT_CONFIGURED',market_records_received:0,evaluation:null};
  const quotaLog=[],eventDiscovery=await fetchEventsDiscovery(env,state.fixture);quotaLog.push(eventDiscovery.quota);let event=eventDiscovery.ok?resolveEvent(eventDiscovery.body,state.fixture):null,eventResolutionSource=event?'events_endpoint':null,featuredDiscovery=null;
  if(!event){featuredDiscovery=await fetchEventsDiscovery(env,state.fixture,{featured:true});quotaLog.push(featuredDiscovery.quota);if(featuredDiscovery.ok){event=resolveEvent(featuredDiscovery.body,state.fixture);if(event)eventResolutionSource='featured_h2h_odds_fallback';}}
  if(!event){const allFailed=!eventDiscovery.ok&&(!featuredDiscovery||!featuredDiscovery.ok),support=allFailed?'UPSTREAM_ERROR':'EVENT_NOT_FOUND';return {market_data:true,p_model_mutated:false,p_model_status:'FROZEN',run_id:state.runId,fixture_id:state.freeze.fixture_id,freeze_receipt_sha256:state.receipt,frozen_at:state.freeze.frozen_at,odds_api_support:support,event_resolution_source:'none',event_resolution_diagnostics:{events_mode:eventDiscovery.mode,events_count:eventDiscovery.body.length,events_attempts:eventDiscovery.attempts,nearby_events:nearby(eventDiscovery.body,state.fixture),featured_mode:featuredDiscovery?.mode||null,featured_count:featuredDiscovery?.body?.length||0,featured_attempts:featuredDiscovery?.attempts||[],nearby_featured_events:nearby(featuredDiscovery?.body||[],state.fixture)},quota:quotaLog,market_records_received:0,evaluation:null};}
  const capturedAt=new Date().toISOString(),first=await eventOdds(env,event,requested);quotaLog.push(first.quota);let rows=[],used=[],unsupported=[],probed=false;
  if(first.res.ok){rows=normalizeRows(first.body,event,state.freeze.fixture_id,capturedAt);used=[...requested];}
  else if(code(first.body)==='INVALID_MARKET'){probed=true;for(const key of requested){const one=await eventOdds(env,event,[key]);quotaLog.push(one.quota);if(one.res.ok){used.push(key);rows.push(...normalizeRows(one.body,event,state.freeze.fixture_id,capturedAt));}else if(code(one.body)==='INVALID_MARKET')unsupported.push(key);else return {market_data:true,p_model_mutated:false,p_model_status:'FROZEN',run_id:state.runId,fixture_id:state.freeze.fixture_id,freeze_receipt_sha256:state.receipt,frozen_at:state.freeze.frozen_at,odds_api_support:'UPSTREAM_ERROR',event:{event_id:event.id,home_team:event.home_team,away_team:event.away_team,commence_time:event.commence_time,team_orientation:eventOrientation(event,state.fixture)},upstream_error:providerProblem(one.res,one.body,`props_${key}`),quota:quotaLog,market_records_received:0,evaluation:null};}}
  else return {market_data:true,p_model_mutated:false,p_model_status:'FROZEN',run_id:state.runId,fixture_id:state.freeze.fixture_id,freeze_receipt_sha256:state.receipt,frozen_at:state.freeze.frozen_at,odds_api_support:'UPSTREAM_ERROR',event:{event_id:event.id,home_team:event.home_team,away_team:event.away_team,commence_time:event.commence_time,team_orientation:eventOrientation(event,state.fixture)},upstream_error:providerProblem(first.res,first.body,'props_bundle'),quota:quotaLog,market_records_received:0,evaluation:null};
  const meta={event_id:event.id,home_team:event.home_team,away_team:event.away_team,commence_time:event.commence_time,team_orientation:eventOrientation(event,state.fixture)};
  if(used.length===0)return {market_data:true,p_model_mutated:false,p_model_status:'FROZEN',run_id:state.runId,fixture_id:state.freeze.fixture_id,freeze_receipt_sha256:state.receipt,frozen_at:state.freeze.frozen_at,odds_api_support:'UNSUPPORTED_MARKET',event:meta,event_resolution_source:eventResolutionSource,markets_requested:requested,markets_used:[],markets_unsupported:unsupported,fallback_probed_individually:probed,quota:quotaLog,market_records_received:0,evaluation:null};
  const unique=new Map();for(const row of rows){const k=[norm(row.player_name),row.stat_type,row.side,row.threshold].join('|'),old=unique.get(k);if(!old||row.decimal_price>old.decimal_price)unique.set(k,row);}rows=[...unique.values()];if(rows.length===0)return {market_data:true,p_model_mutated:false,p_model_status:'FROZEN',run_id:state.runId,fixture_id:state.freeze.fixture_id,freeze_receipt_sha256:state.receipt,frozen_at:state.freeze.frozen_at,odds_api_support:'SUPPORTED_EMPTY',event:meta,event_resolution_source:eventResolutionSource,markets_requested:requested,markets_used:used,markets_unsupported:unsupported,fallback_probed_individually:probed,quota:quotaLog,market_records_received:0,evaluation:null};need(rows.length<=MAX_MARKETS,`Odds API normalized market rows exceed ${MAX_MARKETS}`);
  const evaluation=await evaluate({run_id:state.runId,expected_freeze_receipt_sha256:state.receipt,markets:rows},env);return {market_data:true,p_model_mutated:false,p_model_status:'FROZEN',run_id:state.runId,fixture_id:state.freeze.fixture_id,freeze_receipt_sha256:state.receipt,frozen_at:state.freeze.frozen_at,odds_api_support:'SUPPORTED_WITH_ROWS',event:meta,event_resolution_source:eventResolutionSource,markets_requested:requested,markets_used:used,markets_unsupported:unsupported,fallback_probed_individually:probed,quota:quotaLog,market_records_received:rows.length,evaluation};
}

export default {async fetch(request,env){try{if(request.method==='GET'&&new URL(request.url).pathname==='/health')return response({ok:true,service:'nbl-player-props-market-v1',version:'1.3.1',market_data:true,research_base:researchBase(env),supported_stats:['assists','rebounds'],supported_sources:['odds_api','screenshot','public_web'],odds_api_sport:ODDS_SPORT,odds_api_fetch_configured:Boolean(env?.ODDS_API_KEY),odds_api_markets:DEFAULT_ODDS_MARKETS,discovery_retry:'windowed_then_unfiltered'});if(request.method==='POST'&&new URL(request.url).pathname==='/v1/fetch-odds-api'){const raw=await request.text();need(raw.length<=50_000,'Request too large');return response(await fetchAndEvaluateOddsApiV130(JSON.parse(raw),env));}return legacy.fetch(request,env);}catch(error){return response({market_data:true,p_model_mutated:false,error:error.message},422);}}};
