import test from 'node:test';
import assert from 'node:assert/strict';
import {evaluate,fetchAndEvaluateOddsApi,resolveOddsEvent,normalizeOddsRows,sha256Json} from './index.js';

const RUN='a'.repeat(64),RECEIPT='b'.repeat(64),FROZEN_AT='2026-09-11T09:51:10.890Z';
const frozenPlayer={player_id:'p1',player_name:'Test Guard',team:'Adelaide 36ers',heads:{
  assists:{confidence:'B',fragility:'LOW',probability_grid:{half_point_grid:[{line:4.5,over:.55,push:0,under:.45}],integer_push_grid:[{line:5,over:.35,push:.2,under:.45}]}},
  rebounds:{confidence:'C',fragility:'MEDIUM',probability_grid:{half_point_grid:[{line:5.5,over:.4,push:0,under:.6}],integer_push_grid:[{line:6,over:.25,push:.15,under:.6}]}}
}};
const PLAYER_HASH=await sha256Json(frozenPlayer);
const fixture={id:'fixture-1',start_time:'2026-09-19T09:30:00Z',home_team:{id:'h',name:'Melbourne United'},away_team:{id:'a',name:'Adelaide 36ers'}};
const runBody={status:'FROZEN',lock:{fixture},freeze:{status:'FROZEN',fixture_id:'fixture-1',freeze_receipt_sha256:RECEIPT,frozen_at:FROZEN_AT,players:[{player_key:'id:p1',player_model_sha256:PLAYER_HASH,player_id:'p1',player_name:'Test Guard',team:'Adelaide 36ers'}]}};
const playerBody={freeze_receipt_sha256:RECEIPT,frozen_at:FROZEN_AT,player_model_sha256:PLAYER_HASH,player:frozenPlayer};
const oddsEvent={id:'evt1',sport_key:'basketball_nbl',commence_time:'2026-09-19T09:30:00Z',home_team:'Melbourne United',away_team:'Adelaide 36ers'};
const oddsBody={...oddsEvent,bookmakers:[{key:'sportsbet',title:'SportsBet',markets:[{key:'player_assists',outcomes:[{name:'Over',description:'Test Guard',price:2.05,point:4.5},{name:'Under',description:'Test Guard',price:1.75,point:4.5}]},{key:'player_rebounds',outcomes:[{name:'Over',description:'Test Guard',price:2.4,point:5.5}]}]}]};
function market(overrides={}){return {fixture_id:'fixture-1',player_name:'Test Guard',stat_type:'assists',side:'over',threshold:4.5,decimal_price:2.0,bookmaker:'Book A',captured_at:'2026-09-11T10:00:00Z',source_type:'screenshot',...overrides};}
function jr(x,status=200,headers={}){return new Response(JSON.stringify(x),{status,headers:{'content-type':'application/json',...headers}});}
function installFetch({run=runBody,player=playerBody,events=[oddsEvent],props=oddsBody,propsStatus=200,propsError=null}={}){
 const calls=[];globalThis.fetch=async input=>{const url=String(input);calls.push(url);if(url.includes(`/v1/match-runs/${RUN}/players/`))return jr(player);if(url.endsWith(`/v1/match-runs/${RUN}`))return jr(run);if(url.includes('/v4/sports/basketball_nbl/events?'))return jr(events,200,{'x-requests-used':'1'});if(url.includes('/v4/sports/basketball_nbl/events/evt1/odds?'))return propsError?jr(propsError,propsStatus):jr(props,propsStatus,{'x-requests-used':'5','x-requests-remaining':'19995'});return jr({error:'unexpected '+url},404);};return calls;
}
const env={RESEARCH_BASE:'https://research.example.workers.dev',ODDS_API_KEY:'secret'};

test('manual evaluation still refuses pre-freeze market rows',async()=>{const old=globalThis.fetch;try{installFetch();await assert.rejects(()=>evaluate({run_id:RUN,expected_freeze_receipt_sha256:RECEIPT,markets:[market({captured_at:'2026-09-11T09:00:00Z'})]},env),/predates/);}finally{globalThis.fetch=old;}});
test('resolves exact frozen NBL event',()=>assert.equal(resolveOddsEvent([oddsEvent],fixture).id,'evt1'));
test('normalizes Odds API player props to canonical rows',()=>{const rows=normalizeOddsRows(oddsBody,oddsEvent,'fixture-1','2026-09-11T10:00:00Z');assert.equal(rows.length,3);assert.deepEqual(new Set(rows.map(x=>x.stat_type)),new Set(['assists','rebounds']));assert.equal(rows[0].source_type,'odds_api');});
test('Odds API retrieval happens only after frozen run verification and evaluates rows',async()=>{const old=globalThis.fetch;try{const calls=installFetch();const out=await fetchAndEvaluateOddsApi({run_id:RUN,expected_freeze_receipt_sha256:RECEIPT},env);assert.equal(out.odds_api_support,'SUPPORTED_WITH_ROWS');assert.equal(out.evaluation.p_model_status,'FROZEN');assert.equal(out.evaluation.p_model_mutated,false);assert.ok(calls[0].endsWith(`/v1/match-runs/${RUN}`));assert.ok(calls.findIndex(x=>x.includes('/v4/sports/basketball_nbl/events?'))>0);assert.equal(out.evaluation.best_single.player_name,'Test Guard');}finally{globalThis.fetch=old;}});
test('missing key returns NOT_CONFIGURED after freeze verification',async()=>{const old=globalThis.fetch;try{const calls=installFetch();const out=await fetchAndEvaluateOddsApi({run_id:RUN,expected_freeze_receipt_sha256:RECEIPT},{RESEARCH_BASE:env.RESEARCH_BASE});assert.equal(out.odds_api_support,'NOT_CONFIGURED');assert.equal(calls.filter(x=>x.includes('the-odds-api')).length,0);}finally{globalThis.fetch=old;}});
test('invalid alternate markets fall back to base markets',async()=>{const old=globalThis.fetch;try{let n=0;globalThis.fetch=async input=>{const url=String(input);if(url.endsWith(`/v1/match-runs/${RUN}`))return jr(runBody);if(url.includes(`/v1/match-runs/${RUN}/players/`))return jr(playerBody);if(url.includes('/events?'))return jr([oddsEvent]);if(url.includes('/events/evt1/odds?')){n++;if(n===1)return jr({error_code:'INVALID_MARKET',message:'bad alt'},422);return jr(oddsBody);}return jr({},404);};const out=await fetchAndEvaluateOddsApi({run_id:RUN,expected_freeze_receipt_sha256:RECEIPT},env);assert.equal(out.odds_api_support,'SUPPORTED_WITH_ROWS');assert.equal(out.alternate_fallback_attempted,true);assert.deepEqual(out.markets_used,['player_assists','player_rebounds']);assert.equal(n,2);}finally{globalThis.fetch=old;}});
test('unsupported base markets return explicit support status, not fabricated rows',async()=>{const old=globalThis.fetch;try{let n=0;globalThis.fetch=async input=>{const url=String(input);if(url.endsWith(`/v1/match-runs/${RUN}`))return jr(runBody);if(url.includes('/events?'))return jr([oddsEvent]);if(url.includes('/events/evt1/odds?')){n++;return jr({error_code:'INVALID_MARKET',message:'not supported'},422);}return jr({},404);};const out=await fetchAndEvaluateOddsApi({run_id:RUN,expected_freeze_receipt_sha256:RECEIPT,markets:['player_assists','player_rebounds']},env);assert.equal(out.odds_api_support,'UNSUPPORTED_MARKET');assert.equal(out.market_records_received,0);assert.equal(n,1);}finally{globalThis.fetch=old;}});
