import test from 'node:test';
import assert from 'node:assert/strict';
import { probabilityGrid, computeGameFreeze, computeSlateFreeze } from './freeze_core.js';

const h='a'.repeat(64);
const evidence=[{evidence_id:'e1',url:'https://example.com/a',title:'Rotation',checked_at:'2026-09-08T07:00:00Z',source_tier:1,evidence_type:'ROLE'}];
const roleResearch={rotation_role:'Starting guard role',hierarchy_and_competition:'Primary guard among current handlers',lineup_dependencies:'Creation changes with secondary guard availability',role_breakpoints:'Role falls if rotation changes',change_summary:'Current role rebuilt from present roster',evidence_ids:['e1']};
function player(id='100',role='RETURNING_CHANGED'){return {player_id:id,player_name:'Test Guard',team_id:'2',team:'Boston Celtics',availability:'ACTIVE',role_state:role,projected_minutes:{low:30,mean:34,high:37},expected_starter_probability:.9,evidence_ids:['e1'],role_research:roleResearch,confidence_inputs:{current:true},fragility_inputs:{late:false},stat_context:{assists:{causal_pathway:'More creation',evidence_ids:['e1'],current_opportunity:{expected_assist_share:.31,expected_team_assists:27,expected_opponent_assists_allowed:25,expected_possessions:101,evidence_ids:['e1']}},rebounds:{causal_pathway:'Stable boards',evidence_ids:['e1'],current_opportunity:{expected_rebound_share:.08,expected_team_rebounds:44,expected_opponent_rebounds_allowed:43,expected_possessions:101,evidence_ids:['e1']}}}};}
function research(game='4019999999'){return {schema_version:'nba_game_research_v1',market_data:false,run_mode:'BOTH',game_id:game,slate_date_et:'2026-10-20',fixture:{season:2027,home_team:{id:'2',name:'Boston Celtics'},away_team:{id:'18',name:'New York Knicks'},start_time_utc:'2026-10-21T00:00:00Z',evidence_ids:['e1']},evidence,specialist_metrics:{potential_assists:{status:'UNAVAILABLE'}},players:[player()]};}
function center(k){if(k.startsWith('minutes_'))return 30;if(k.startsWith('start_rate')||k==='starter_prev')return .5;if(k.includes('assist_share'))return .2;if(k.includes('rebound_share'))return .1;if(k.includes('team_assists')||k.includes('opponent_assists'))return 25;if(k.includes('team_rebounds')||k.includes('opponent_rebounds'))return 43;if(k.includes('possessions'))return 100;return 1;}
function scale(k){if(k.startsWith('minutes_'))return 5;if(k.startsWith('start_rate')||k==='starter_prev')return .3;if(k.includes('share'))return .1;if(k.includes('possessions'))return 5;if(k.includes('assists')||k.includes('rebounds'))return 5;return 1;}
function artifact(head){const features=head==='assists'?['minutes_l5','minutes_l10','start_rate_l5','start_rate_l10','starter_prev','assist_share_l5','assist_share_l10','team_assists_l5','team_assists_l10','opponent_assists_allowed_l5','opponent_assists_allowed_l10','team_possessions_l5','team_possessions_l10']:['minutes_l5','minutes_l10','start_rate_l5','start_rate_l10','starter_prev','rebound_share_l5','rebound_share_l10','team_rebounds_l5','team_rebounds_l10','opponent_rebounds_allowed_l5','opponent_rebounds_allowed_l10','team_possessions_l5','team_possessions_l10'];return {status:'PROMOTED_CORE_V1',market_data:false,family:'regularized_poisson_glm',head,features,medians:features.map(center),centers:features.map(center),scales:features.map(scale),coefficients:features.map(()=>.01),intercept:0,dispersion_alpha:.2,model_version:`NBA_${head}_V1`,promotion_receipt_sha256:h,holdout_use_rule:'PASS_FAIL_REVIEW_ONLY_NO_MODEL_FAMILY_RESELECTION'};}
function priors(){const make=head=>({prior_snapshot_sha256:h,base_features:Object.fromEntries(artifact(head).features.map(k=>[k,center(k)]))});return [{player_id:'100',heads:{assists:make('assists'),rebounds:make('rebounds')}}];}

test('integer probability grid is push-aware and partitions exactly',()=>{const g=probabilityGrid(6,.2,30);const r=g.integer_push_grid.find(x=>x.line===6);assert.ok(r.push>0);assert.ok(Math.abs(r.over+r.push+r.under-1)<1e-9);});
test('game freeze computes means server-side and commits player/head hashes',async()=>{const g=await computeGameFreeze({research:research(),qbaseArtifacts:{assists:artifact('assists'),rebounds:artifact('rebounds')},priorSnapshots:priors(),frozenAt:'2026-10-20T12:00:00Z'});assert.equal(g.status,'FROZEN');assert.equal(g.players.length,1);assert.equal(g.players[0].heads.assists.final_mean>0,true);assert.equal(g.players[0].heads.rebounds.final_mean>0,true);assert.match(g.players[0].player_model_sha256,/^[0-9a-f]{64}$/);assert.match(g.players[0].heads.assists.head_model_sha256,/^[0-9a-f]{64}$/);assert.match(g.players[0].heads.rebounds.head_model_sha256,/^[0-9a-f]{64}$/);assert.match(g.freeze_receipt_sha256,/^[0-9a-f]{64}$/);});
test('rookie without promoted prior competition route is excluded not fabricated',async()=>{const r=research();r.players=[player('200','ROOKIE')];const g=await computeGameFreeze({research:r,qbaseArtifacts:{assists:artifact('assists'),rebounds:artifact('rebounds')},priorSnapshots:[],frozenAt:'2026-10-20T12:00:00Z'});assert.equal(g.players.length,0);assert.equal(g.exclusions[0].reason,'NO_PROMOTED_PRIOR_COMP_TRANSLATION');});
test('whole slate freeze requires every eligible game research checkpoint',async()=>{await assert.rejects(()=>computeSlateFreeze({slateDateEt:'2026-10-20',runMode:'BOTH',eligibleGameIds:['4019999999','4019999998'],researchByGame:{'4019999999':research('4019999999')},qbaseArtifacts:{assists:artifact('assists'),rebounds:artifact('rebounds')},priorsByGame:{'4019999999':priors()},frozenAt:'2026-10-20T12:00:00Z'}),/research missing/);});
test('whole slate freeze emits one immutable receipt and integrity index',async()=>{const ids=['4019999999','4019999998'];const out=await computeSlateFreeze({slateDateEt:'2026-10-20',runMode:'BOTH',eligibleGameIds:ids,researchByGame:Object.fromEntries(ids.map(id=>[id,research(id)])),qbaseArtifacts:{assists:artifact('assists'),rebounds:artifact('rebounds')},priorsByGame:Object.fromEntries(ids.map(id=>[id,priors()])),frozenAt:'2026-10-20T12:00:00Z'});assert.deepEqual(out.eligible_game_ids,ids);assert.equal(out.games.length,2);assert.equal(out.integrity_index.length,2);for(let i=0;i<2;i++){const player=out.games[i].players[0],idx=out.integrity_index[i].players[0];assert.equal(idx.player_model_sha256,player.player_model_sha256);assert.equal(idx.heads.assists,player.heads.assists.head_model_sha256);assert.equal(idx.heads.rebounds,player.heads.rebounds.head_model_sha256);}assert.match(out.freeze_receipt_sha256,/^[0-9a-f]{64}$/);});
