import test from 'node:test';
import assert from 'node:assert/strict';
import { validateResearchCheckpoint } from './research_contract.js';
import { buildTransformsFromResearch } from './research_to_transforms.js';

const evidence=[{evidence_id:'e1',url:'https://example.com/a',title:'Rotation report',checked_at:'2026-09-08T07:00:00Z',published_at:'2026-09-08T06:00:00Z',source_tier:1,evidence_type:'ROLE'}];
function player(){return {player_id:'100',player_name:'Test Guard',team_id:'2',team:'Boston Celtics',availability:'ACTIVE',role_state:'RETURNING_CHANGED',projected_minutes:{low:30,mean:34,high:37},expected_starter_probability:.9,evidence_ids:['e1'],role_research:{rotation_role:'Starting lead guard',hierarchy_and_competition:'Primary creator with secondary guard support',lineup_dependencies:'Creation rises when secondary handler sits',role_breakpoints:'Minutes or creation fall if second unit role returns',change_summary:'More on-ball work after roster change',evidence_ids:['e1']},confidence_inputs:{current_role:true},fragility_inputs:{late_news:false},stat_context:{assists:{causal_pathway:'Primary creator with more on-ball reps',evidence_ids:['e1'],current_opportunity:{expected_assist_share:.31,expected_team_assists:27,expected_opponent_assists_allowed:25,expected_possessions:101,evidence_ids:['e1']}},rebounds:{causal_pathway:'Stable guard rebound role',evidence_ids:['e1'],current_opportunity:{expected_rebound_share:.08,expected_team_rebounds:44,expected_opponent_rebounds_allowed:43,expected_possessions:101,evidence_ids:['e1']}}}};}
function checkpoint(){return {schema_version:'nba_game_research_v1',market_data:false,run_mode:'BOTH',game_id:'4019999999',slate_date_et:'2026-10-20',fixture:{season:2027,home_team:{id:'2',name:'Boston Celtics'},away_team:{id:'18',name:'New York Knicks'},start_time_utc:'2026-10-21T00:00:00Z',evidence_ids:['e1']},evidence,specialist_metrics:{potential_assists:{status:'UNAVAILABLE'}},players:[player()]};}
function artifact(head){const features=head==='assists'?['minutes_l5','minutes_l10','start_rate_l5','start_rate_l10','starter_prev','assist_share_l5','assist_share_l10','team_assists_l5','team_assists_l10','opponent_assists_allowed_l5','opponent_assists_allowed_l10','team_possessions_l5','team_possessions_l10']:['minutes_l5','minutes_l10','start_rate_l5','start_rate_l10','starter_prev','rebound_share_l5','rebound_share_l10','team_rebounds_l5','team_rebounds_l10','opponent_rebounds_allowed_l5','opponent_rebounds_allowed_l10','team_possessions_l5','team_possessions_l10'];return {family:'regularized_poisson_glm',head,features,medians:features.map(()=>1),centers:features.map((_,i)=>features[i].includes('share')?.2:(features[i].includes('possessions')?100:25)),scales:features.map((_,i)=>features[i].includes('share')?.1:(features[i].includes('possessions')?5:5)),coefficients:features.map(()=>.01),intercept:0,dispersion_alpha:.2};}

test('research contract requires market-blind evidence-bound current opportunity and role audit',()=>{const out=validateResearchCheckpoint(checkpoint(),Date.parse('2026-09-08T08:00:00Z'));assert.equal(out.ok,true);assert.deepEqual(out.heads,['assists','rebounds']);assert.deepEqual(out.fixture_team_ids,['2','18']);});
test('market leakage is rejected before freeze',()=>{const c=checkpoint();c.players[0].sportsbook='x';assert.throws(()=>validateResearchCheckpoint(c,Date.parse('2026-09-08T08:00:00Z')),/market boundary/);});
test('player team identity and exact name must belong to fixture lock',()=>{const c=checkpoint();c.players[0].team_id='99';assert.throws(()=>validateResearchCheckpoint(c,Date.parse('2026-09-08T08:00:00Z')),/team_id not in fixture/);const d=checkpoint();d.players[0].team='Wrong Team';assert.throws(()=>validateResearchCheckpoint(d,Date.parse('2026-09-08T08:00:00Z')),/team name mismatch/);});
test('role research cannot be omitted from a completed checkpoint',()=>{const c=checkpoint();delete c.players[0].role_research;assert.throws(()=>validateResearchCheckpoint(c,Date.parse('2026-09-08T08:00:00Z')),/role_research required/);});
test('projected minutes cannot exceed a full regulation game',()=>{const c=checkpoint();c.players[0].projected_minutes.high=49;assert.throws(()=>validateResearchCheckpoint(c,Date.parse('2026-09-08T08:00:00Z')),/minutes.high invalid/);});
test('assists research becomes only typed feature transforms including current opponent',()=>{const t=buildTransformsFromResearch(artifact('assists'),player());assert.deepEqual(t.map(x=>x.type),['MINUTES_RECOMPUTE','ROLE_OPPORTUNITY_RECOMPUTE','LINEUP_DEPENDENCY_RECOMPUTE']);assert.equal(t[1].inputs.assist_share_l5,.31);assert.equal(t[1].inputs.team_assists_l10,27);assert.equal(t[2].inputs.team_possessions_l5,101);assert.equal(t[2].inputs.opponent_assists_allowed_l10,25);assert.equal('mean' in t[1],false);});
test('rebounds research maps to rebound and opponent opportunity rather than assist fields',()=>{const t=buildTransformsFromResearch(artifact('rebounds'),player());assert.equal(t[1].inputs.rebound_share_l5,.08);assert.equal(t[1].inputs.team_rebounds_l10,44);assert.equal(t[2].inputs.opponent_rebounds_allowed_l5,43);assert.equal(t[1].inputs.assist_share_l5,undefined);});
