import test from 'node:test';
import assert from 'node:assert/strict';
import { buildResearchSeed } from './research_seed.js';

const H='a'.repeat(64),P='b'.repeat(64);const fixture={game_id:'4019999999',slate_date_et:'2026-10-20',season:2027,start_time_utc:'2026-10-21T00:00:00Z',home_team:{id:'2',name:'Boston Celtics'},away_team:{id:'18',name:'New York Knicks'},status:'SCHEDULED',source:'ESPN_SCOREBOARD_NON_MARKET'};
function art(head){const features=head==='assists'?['season_games_before','team_games_before','team_rest_days','player_days_since_last_game','team_changed_since_last_game','minutes_l5','assist_share_l5','team_assists_l5','opponent_assists_allowed_l5']:['season_games_before','team_games_before','team_rest_days','player_days_since_last_game','team_changed_since_last_game','minutes_l5','rebound_share_l5','team_rebounds_l5','opponent_rebounds_allowed_l5'];return {status:'PROMOTED_CORE_V1',market_data:false,family:'regularized_poisson_glm',head,features,medians:features.map(()=>1),centers:features.map(()=>1),scales:features.map(()=>1),coefficients:features.map(()=>.01),intercept:1,dispersion_alpha:.2,model_version:`NBA_${head}_V1`,promotion_receipt_sha256:P};}
function assets(){return {manifest:{asset_revision:'NBA_PLAYER_PROPS_V1.0.0',history_sha256:H},qbase_artifacts:{assists:art('assists'),rebounds:art('rebounds')},prior_pack:{schema_version:'nba_runtime_prior_pack_v1',market_data:false,history_sha256:H,pack_sha256:H,players:{'100':{last_team_id:'18',last_season:2026,last_game_start_utc:'2026-04-15T00:00:00Z',career_games:200,games_by_season:{'2026':70},features:{minutes_l5:33,minutes_l10:32,start_rate_l5:1,start_rate_l10:.9,assist_share_l5:.3,assist_share_l10:.28,assists_l5:7,assists_l10:6.5,rebound_share_l5:.1,rebound_share_l10:.09,rebounds_l5:5,rebounds_l10:4.8}}},teams:{'2':{last_game_start_utc:'2026-04-17T00:00:00Z',games_by_season:{'2026':82},features:{team_assists_l5:27,team_assists_l10:26,team_rebounds_l5:44,team_rebounds_l10:43,team_possessions_l5:100,team_possessions_l10:99,assists_allowed_l5:24,assists_allowed_l10:25,rebounds_allowed_l5:42,rebounds_allowed_l10:43}},'18':{last_game_start_utc:'2026-04-18T00:00:00Z',games_by_season:{'2026':82},features:{team_assists_l5:25,team_assists_l10:24,team_rebounds_l5:42,team_rebounds_l10:41,team_possessions_l5:99,team_possessions_l10:98,assists_allowed_l5:23,assists_allowed_l10:24,rebounds_allowed_l5:41,rebounds_allowed_l10:42}}}}};}
const rosterProvider=async id=>({market_data:false,team_id:String(id),season:2027,source:{provider:'ESPN',url:`https://example.com/${id}`,checked_at:'2026-09-08T08:00:00Z'},athletes:id==='2'?[{player_id:'100',player_name:'Veteran',team_id:'2',position:'G',roster_status:'active',injuries:[]},{player_id:'999',player_name:'Rookie',team_id:'2',position:'F',roster_status:'active',injuries:[]}]:Array.from({length:5},(_,i)=>({player_id:String(200+i),player_name:`Away ${i}`,team_id:'18',position:'G',roster_status:'active',injuries:[]}))});

test('research seed labels historical team change and new-to-NBA players distinctly',async()=>{const s=await buildResearchSeed(fixture,assets(),{rosterProvider});const veteran=s.home_roster.find(x=>x.player_id==='100'),rookie=s.home_roster.find(x=>x.player_id==='999');assert.equal(veteran.nba_history_status,'NBA_HISTORY_AVAILABLE_TEAM_CHANGED');assert.equal(veteran.qbase_prior.assists.status,'SERVER_HISTORICAL_QBASE_PRIOR');assert.equal(rookie.nba_history_status,'PRIOR_COMP_TRANSLATION_REQUIRED');assert.equal(rookie.qbase_prior,null);assert.equal(s.market_data,false);});
test('research seed exposes compact team environment priors as prior-only anchors',async()=>{const s=await buildResearchSeed(fixture,assets(),{rosterProvider});assert.equal(s.team_environment_prior.home.features.team_assists_l5,27);assert.equal(s.team_environment_prior.home.features.team_possessions_l10,99);assert.equal(s.team_environment_prior.away.features.rebounds_allowed_l5,41);assert.match(s.research_rule,/TEAM ENVIRONMENT VALUE ABOVE IS A HISTORICAL PRIOR ONLY/);});
test('research seed contains no client-final probability or sportsbook material',async()=>{const s=await buildResearchSeed(fixture,assets(),{rosterProvider});const text=JSON.stringify(s).toLowerCase();assert.equal(text.includes('sportsbook'),false);assert.equal(text.includes('bookmaker'),false);assert.match(s.research_rule,/HISTORICAL PRIOR ONLY/);});
