/** Market-blind research seed: current roster identity + historical NBA/QBASE priors. */
import { fetchRoster } from './roster_source.js';
import { assembleBaseFeatures } from './runtime_prior.js';
import { scoreQbase } from './runtime_score.js';
import { marketKeyHits } from './research_contract.js';
const need=(ok,msg)=>{if(!ok) throw new Error(msg);};
const compactFeatures=f=>({minutes_l5:f?.minutes_l5??null,minutes_l10:f?.minutes_l10??null,start_rate_l5:f?.start_rate_l5??null,start_rate_l10:f?.start_rate_l10??null,assists_l5:f?.assists_l5??null,assists_l10:f?.assists_l10??null,assist_share_l5:f?.assist_share_l5??null,assist_share_l10:f?.assist_share_l10??null,rebounds_l5:f?.rebounds_l5??null,rebounds_l10:f?.rebounds_l10??null,rebound_share_l5:f?.rebound_share_l5??null,rebound_share_l10:f?.rebound_share_l10??null});
const compactTeamFeatures=f=>({team_possessions_l5:f?.team_possessions_l5??null,team_possessions_l10:f?.team_possessions_l10??null,team_assists_l5:f?.team_assists_l5??null,team_assists_l10:f?.team_assists_l10??null,team_rebounds_l5:f?.team_rebounds_l5??null,team_rebounds_l10:f?.team_rebounds_l10??null,assists_allowed_l5:f?.assists_allowed_l5??null,assists_allowed_l10:f?.assists_allowed_l10??null,rebounds_allowed_l5:f?.rebounds_allowed_l5??null,rebounds_allowed_l10:f?.rebounds_allowed_l10??null});

async function decorateRoster(roster,fixture,assets){const rows=[];for(const p of roster.athletes){const hist=assets.prior_pack.players?.[String(p.player_id)];if(!hist){rows.push({...p,nba_history_status:'PRIOR_COMP_TRANSLATION_REQUIRED',historical_prior:null,qbase_prior:null});continue;}let assembled;try{assembled=assembleBaseFeatures(assets.prior_pack,p,fixture);}catch(e){rows.push({...p,nba_history_status:'NBA_HISTORY_BLOCKED_TEMPORAL_OR_TEAM_CONTEXT',historical_prior:{last_team_id:hist.last_team_id,last_season:hist.last_season,last_game_start_utc:hist.last_game_start_utc,career_games:hist.career_games},qbase_prior:null,block_reason:e.message});continue;}const heads={};for(const head of ['assists','rebounds']){const artifact=assets.qbase_artifacts[head],base={};for(const name of artifact.features)base[name]=assembled.feature_context[name]??null;const score=await scoreQbase(artifact,base);heads[head]={status:'SERVER_HISTORICAL_QBASE_PRIOR',model_version:artifact.model_version,mean:score.mean,dispersion_alpha:score.dispersion_alpha,quant_input_receipt_sha256:score.quant_input_receipt_sha256};}rows.push({...p,nba_history_status:String(hist.last_team_id)===String(p.team_id)?'NBA_HISTORY_AVAILABLE_SAME_TEAM':'NBA_HISTORY_AVAILABLE_TEAM_CHANGED',historical_prior:{last_team_id:String(hist.last_team_id),last_season:hist.last_season,last_game_start_utc:hist.last_game_start_utc,career_games:hist.career_games,features:compactFeatures(hist.features)},qbase_prior:heads});}return rows;}
function teamPrior(pack,team){const row=pack.teams?.[String(team.id)];return row?{team_id:String(team.id),team_name:String(team.name),last_game_start_utc:row.last_game_start_utc,features:compactTeamFeatures(row.features)}:{team_id:String(team.id),team_name:String(team.name),last_game_start_utc:null,features:null,status:'NO_ACCEPTED_TEAM_PRIOR'};}

export async function buildResearchSeed(fixture,assets,{rosterProvider=fetchRoster,nowMs=Date.now()}={}){
  need(fixture&&assets?.prior_pack&&assets?.qbase_artifacts,'fixture and runtime assets required');const [home,away]=await Promise.all([rosterProvider(fixture.home_team.id,{expectedSeason:fixture.season,nowMs}),rosterProvider(fixture.away_team.id,{expectedSeason:fixture.season,nowMs})]);
  const seed={schema_version:'nba_game_research_seed_v1',market_data:false,fixture,roster_source_receipts:{home:home.source||null,away:away.source||null},team_environment_prior:{home:teamPrior(assets.prior_pack,fixture.home_team),away:teamPrior(assets.prior_pack,fixture.away_team)},home_roster:await decorateRoster(home,fixture,assets),away_roster:await decorateRoster(away,fixture,assets),runtime_asset_revision:assets.manifest.asset_revision,history_sha256:assets.manifest.history_sha256,qbase_heads:Object.fromEntries(['assists','rebounds'].map(h=>[h,{model_version:assets.qbase_artifacts[h].model_version,promotion_receipt_sha256:assets.qbase_artifacts[h].promotion_receipt_sha256}])),specialist_metric_policy:'BASE_V1_WITHOUT_SPECIALIST_METRICS_UNLESS_A_SEPARATE_FEATURE_GATE_IS_PROMOTED',research_rule:'EVERY QBASE AND TEAM ENVIRONMENT VALUE ABOVE IS A HISTORICAL PRIOR ONLY. CURRENT AVAILABILITY, ROTATION, MINUTES, STARTER/CREATOR/FRONTCOURT HIERARCHY, TEAM CHANGES, COACHING, PRESEASON/CAMP, LINEUP DEPENDENCIES AND CURRENT OPPORTUNITY MUST BE RESEARCHED PRE-MARKET BEFORE FREEZE.'};need(marketKeyHits(seed).length===0,'research seed market boundary failed');return seed;
}
