import test from 'node:test';
import assert from 'node:assert/strict';
import { assembleBaseFeatures, buildPriorSnapshotsForResearch } from './runtime_prior.js';

const H='a'.repeat(64);
function pack(){return {schema_version:'nba_runtime_prior_pack_v1',market_data:false,history_sha256:H,pack_sha256:H,players:{'100':{player_id:'100',last_team_id:'2',last_game_start_utc:'2026-04-15T00:00:00Z',last_season:2026,games_by_season:{'2026':70},features:{starter_prev:1,start_rate_l5:1,start_rate_l10:.9,minutes_l3:34,minutes_l5:33,minutes_l10:32,minutes_l20:31,assists_l3:8,assists_l5:7,assists_l10:6.5,assists_l20:6,assists_per_min_l5:.21,assists_per_min_l10:.2,assist_share_l5:.3,assist_share_l10:.28,turnovers_l5:2.5,fga_l5:14,rebounds_l3:5,rebounds_l5:5.5,rebounds_l10:5,rebounds_l20:4.8,offensive_rebounds_l5:.5,defensive_rebounds_l5:5,rebounds_per_min_l5:.16,rebounds_per_min_l10:.15,rebound_share_l5:.12,rebound_share_l10:.11}}},teams:{'2':{team_id:'2',last_game_start_utc:'2026-04-17T00:00:00Z',games_by_season:{'2026':82},features:{team_possessions_l5:99,team_possessions_l10:100,team_assists_l5:27,team_assists_l10:26,team_rebounds_l5:45,team_rebounds_l10:44,assists_allowed_l5:24,assists_allowed_l10:25,rebounds_allowed_l5:43,rebounds_allowed_l10:44}},'18':{team_id:'18',last_game_start_utc:'2026-04-18T00:00:00Z',games_by_season:{'2026':82},features:{team_possessions_l5:98,team_possessions_l10:99,team_assists_l5:25,team_assists_l10:24,team_rebounds_l5:43,team_rebounds_l10:42,assists_allowed_l5:23,assists_allowed_l10:22,rebounds_allowed_l5:41,rebounds_allowed_l10:40}}}};}
const fixture={season:2027,home_team:{id:'2',name:'Boston Celtics'},away_team:{id:'18',name:'New York Knicks'},start_time_utc:'2026-10-21T00:00:00Z'};
const player={player_id:'100',team_id:'2'};
function artifact(head){const features=head==='assists'?['season_games_before','team_games_before','team_rest_days','player_days_since_last_game','team_changed_since_last_game','minutes_l5','assist_share_l5','team_assists_l5','opponent_assists_allowed_l5']:['season_games_before','team_games_before','team_rest_days','player_days_since_last_game','team_changed_since_last_game','minutes_l5','rebound_share_l5','team_rebounds_l5','opponent_rebounds_allowed_l5'];return {family:'regularized_poisson_glm',head,features,medians:features.map(()=>1),centers:features.map(()=>1),scales:features.map(()=>1),coefficients:features.map(()=>.01),intercept:0,dispersion_alpha:.2};}

test('new season resets season/team game counts while retaining prior role features',()=>{const a=assembleBaseFeatures(pack(),player,fixture);assert.equal(a.feature_context.season_games_before,0);assert.equal(a.feature_context.team_games_before,0);assert.equal(a.feature_context.team_changed_since_last_game,0);assert.equal(a.feature_context.minutes_l5,33);assert.equal(a.feature_context.opponent_assists_allowed_l5,23);assert.equal(a.feature_context.team_rest_days,14);});
test('trade is detected from canonical team IDs',()=>{const p=pack();p.players['100'].last_team_id='18';const a=assembleBaseFeatures(p,player,fixture);assert.equal(a.feature_context.team_changed_since_last_game,1);});
test('prior snapshots are head-specific and hashed',async()=>{const research={market_data:false,run_mode:'BOTH',game_id:'4019999999',fixture,players:[player]};const out=await buildPriorSnapshotsForResearch(pack(),research,{assists:artifact('assists'),rebounds:artifact('rebounds')});assert.equal(out.length,1);assert.match(out[0].heads.assists.prior_snapshot_sha256,/^[0-9a-f]{64}$/);assert.equal(out[0].heads.assists.base_features.opponent_assists_allowed_l5,23);assert.equal(out[0].heads.rebounds.base_features.opponent_rebounds_allowed_l5,41);});
test('future-or-equal prior timestamps are rejected',()=>{const p=pack();p.players['100'].last_game_start_utc=fixture.start_time_utc;assert.throws(()=>assembleBaseFeatures(p,player,fixture),/must precede fixture/);});
