import test from 'node:test';
import assert from 'node:assert/strict';
import { createSlateRun, getResearchBatch, checkpointResearch, freezeSlateRun, invalidateFrozenScope, marketAccessGrant } from './slate_run_core.js';
import { sha256Json } from './runtime_score.js';

const H='a'.repeat(64), evidence=[{evidence_id:'e1',url:'https://example.com/a',title:'Role',checked_at:'2026-09-08T07:00:00Z',source_tier:1,evidence_type:'ROLE'}];
const roleResearch={rotation_role:'Starting guard role',hierarchy_and_competition:'Primary handler among current guards',lineup_dependencies:'Creation changes with secondary guard availability',role_breakpoints:'Role falls if rotation changes',change_summary:'Current role rebuilt from present roster',evidence_ids:['e1']};
function fixture(id){return {game_id:id,slate_date_et:'2026-10-20',season:2027,start_time_utc:'2026-10-21T00:00:00Z',home_team:{id:'2',name:'Boston Celtics',abbreviation:'BOS'},away_team:{id:'18',name:'New York Knicks',abbreviation:'NYK'},status:'SCHEDULED',source:'ESPN_SCOREBOARD_NON_MARKET'};}
function p(){return {player_id:'100',player_name:'Guard',team_id:'2',team:'Boston Celtics',availability:'ACTIVE',role_state:'RETURNING_CHANGED',projected_minutes:{low:30,mean:34,high:37},expected_starter_probability:.9,evidence_ids:['e1'],role_research:roleResearch,confidence_inputs:{x:1},fragility_inputs:{x:1},stat_context:{assists:{causal_pathway:'creation',evidence_ids:['e1'],current_opportunity:{expected_assist_share:.3,expected_team_assists:27,expected_opponent_assists_allowed:25,expected_possessions:101,evidence_ids:['e1']}},rebounds:{causal_pathway:'boards',evidence_ids:['e1'],current_opportunity:{expected_rebound_share:.08,expected_team_rebounds:44,expected_opponent_rebounds_allowed:43,expected_possessions:101,evidence_ids:['e1']}}}};}
function research(id){return {schema_version:'nba_game_research_v1',market_data:false,run_mode:'BOTH',game_id:id,slate_date_et:'2026-10-20',fixture:{season:2027,home_team:{id:'2',name:'Boston Celtics'},away_team:{id:'18',name:'New York Knicks'},start_time_utc:'2026-10-21T00:00:00Z',evidence_ids:['e1']},evidence,specialist_metrics:{potential_assists:{status:'UNAVAILABLE'}},players:[p()]};}
function center(k){if(k.startsWith('minutes_'))return 30;if(k.startsWith('start_rate')||k==='starter_prev')return .5;if(k.includes('assist_share'))return .2;if(k.includes('rebound_share'))return .1;if(k.includes('team_assists')||k.includes('opponent_assists'))return 25;if(k.includes('team_rebounds')||k.includes('opponent_rebounds'))return 43;if(k.includes('possessions'))return 100;return 1;}
function scale(k){if(k.startsWith('minutes_'))return 5;if(k.startsWith('start_rate')||k==='starter_prev')return .3;if(k.includes('share'))return .1;if(k.includes('possessions'))return 5;if(k.includes('assists')||k.includes('rebounds'))return 5;return 1;}
function artifact(head){const f=head==='assists'?['minutes_l5','minutes_l10','start_rate_l5','start_rate_l10','starter_prev','assist_share_l5','assist_share_l10','team_assists_l5','team_assists_l10','opponent_assists_allowed_l5','opponent_assists_allowed_l10','team_possessions_l5','team_possessions_l10']:['minutes_l5','minutes_l10','start_rate_l5','start_rate_l10','starter_prev','rebound_share_l5','rebound_share_l10','team_rebounds_l5','team_rebounds_l10','opponent_rebounds_allowed_l5','opponent_rebounds_allowed_l10','team_possessions_l5','team_possessions_l10'];return {status:'PROMOTED_CORE_V1',market_data:false,family:'regularized_poisson_glm',head,features:f,medians:f.map(center),centers:f.map(center),scales:f.map(scale),coefficients:f.map(()=>.01),intercept:0,dispersion_alpha:.2,model_version:`NBA_${head}_V1`,promotion_receipt_sha256:H,holdout_use_rule:'PASS_FAIL_REVIEW_ONLY_NO_MODEL_FAMILY_RESELECTION'};}
function priors(){const out={};for(const head of ['assists','rebounds'])out[head]={prior_snapshot_sha256:H,base_features:Object.fromEntries(artifact(head).features.map(k=>[k,center(k)]))};return [{player_id:'100',heads:out}];}
async function init(){const ids=['4019999999','4019999998','4019999997'],qa={assists:artifact('assists'),rebounds:artifact('rebounds')},qh={};for(const h of ['assists','rebounds'])qh[h]={model_version:qa[h].model_version,promotion_receipt_sha256:H,artifact_sha256:await sha256Json(qa[h])};return {state:createSlateRun({runId:'run-1',startRequestId:'start-key-001',slateDateEt:'2026-10-20',runMode:'BOTH',eligibleGameIds:ids,fixtures:ids.map(fixture),sourceCommit:'abcdef1',qbaseHeads:qh,createdAt:'2026-10-20T10:00:00Z'}),qa};}
async function completed(){let {state,qa}=await init();state=await checkpointResearch(state,[research('4019999999'),research('4019999998')],Date.parse('2026-10-20T11:00:00Z'));state=await checkpointResearch(state,[research('4019999997')],Date.parse('2026-10-20T11:10:00Z'));return {state,qa};}

test('server exposes only first two pending games until checkpoint',async()=>{const {state}=await init();assert.deepEqual(getResearchBatch(state).batch_game_ids,['4019999999','4019999998']);const s2=await checkpointResearch(state,[research('4019999999'),research('4019999998')],Date.parse('2026-10-20T11:00:00Z'));assert.deepEqual(getResearchBatch(s2).batch_game_ids,['4019999997']);assert.equal(s2.status,'RESEARCH_IN_PROGRESS');});
test('exact checkpoint retry is idempotent after a lost response',async()=>{const {state}=await init(),batch=[research('4019999999'),research('4019999998')];const first=await checkpointResearch(state,batch,Date.parse('2026-10-20T11:00:00Z'));const retried=await checkpointResearch(first,batch,Date.parse('2026-10-20T11:01:00Z'));assert.deepEqual(retried,first);assert.deepEqual(retried.completed_game_ids,['4019999999','4019999998']);assert.equal(retried.research_checkpoints['4019999999'].research_receipt_sha256,first.research_checkpoints['4019999999'].research_receipt_sha256);});
test('changed checkpoint retry is rejected rather than overwriting persisted research',async()=>{const {state}=await init(),batch=[research('4019999999'),research('4019999998')];const first=await checkpointResearch(state,batch,Date.parse('2026-10-20T11:00:00Z'));const changed=[research('4019999999'),research('4019999998')];changed[0].players[0].projected_minutes={low:29,mean:33,high:36};await assert.rejects(()=>checkpointResearch(first,changed,Date.parse('2026-10-20T11:01:00Z')),/checkpoint retry payload changed/);});
test('retry cannot mix an already-persisted game with a new queue game',async()=>{const {state}=await init(),first=await checkpointResearch(state,[research('4019999999')],Date.parse('2026-10-20T11:00:00Z'));await assert.rejects(()=>checkpointResearch(first,[research('4019999999'),research('4019999998')],Date.parse('2026-10-20T11:01:00Z')),/cannot mix retried and new/);});
test('checkpoint cannot mutate a locked fixture while retaining game id',async()=>{const {state}=await init(),r=research('4019999999');r.fixture.start_time_utc='2026-10-21T01:00:00Z';await assert.rejects(()=>checkpointResearch(state,[r],Date.parse('2026-10-20T11:00:00Z')),/kickoff changed/);});
test('whole slate freeze is blocked before all checkpoints',async()=>{const {state,qa}=await init();await assert.rejects(()=>freezeSlateRun(state,{qbaseArtifacts:qa,priorsByGame:{},frozenAt:'2026-10-20T12:00:00Z'}),/RESEARCH_COMPLETE/);});
test('complete run freezes atomically then issues market grant',async()=>{let {state,qa}=await completed();const priorsByGame=Object.fromEntries(state.eligible_game_ids.map(id=>[id,priors()]));state=await freezeSlateRun(state,{qbaseArtifacts:qa,priorsByGame,frozenAt:'2026-10-20T12:00:00Z'});assert.equal(state.status,'FROZEN');const grant=await marketAccessGrant(state);assert.equal(grant.freeze_receipt_sha256,state.freeze.freeze_receipt_sha256);assert.deepEqual(grant.allowed_game_ids,state.eligible_game_ids);});
test('freeze retry returns the exact original immutable freeze without recomputation inputs',async()=>{let {state,qa}=await completed();state=await freezeSlateRun(state,{qbaseArtifacts:qa,priorsByGame:Object.fromEntries(state.eligible_game_ids.map(id=>[id,priors()])),frozenAt:'2026-10-20T12:00:00Z'});const first=structuredClone(state.freeze);const retried=await freezeSlateRun(state);assert.deepEqual(retried.freeze,first);assert.equal(retried.freeze.frozen_at,'2026-10-20T12:00:00Z');assert.equal(retried.freeze.freeze_receipt_sha256,first.freeze_receipt_sha256);});
test('late news invalidates scope without mutating frozen probabilities or receipt',async()=>{let {state,qa}=await completed();state=await freezeSlateRun(state,{qbaseArtifacts:qa,priorsByGame:Object.fromEntries(state.eligible_game_ids.map(id=>[id,priors()])),frozenAt:'2026-10-20T12:00:00Z'});const frozen=structuredClone(state.freeze);state=invalidateFrozenScope(state,{gameIds:['4019999998'],reason:'starter ruled out',detectedAt:'2026-10-20T12:10:00Z'});assert.deepEqual(state.freeze,frozen);const grant=await marketAccessGrant(state);assert.deepEqual(grant.invalidated_game_ids,['4019999998']);assert.deepEqual(grant.allowed_game_ids,['4019999999','4019999997']);const retry=await freezeSlateRun(state);assert.deepEqual(retry.freeze,frozen);assert.equal(retry.status,'FROZEN_BUT_INVALIDATED');});
