import test from 'node:test';
import assert from 'node:assert/strict';
import { deriveSlateRunId, NbaSlateRun } from './index.js';

class MemoryStorage{constructor(){this.map=new Map();}async get(k){return this.map.get(k);}async put(k,v){this.map.set(k,structuredClone(v));}}
function state(overrides={}){return {schema_version:'nba_slate_run_state_v1',market_data:false,run_id:'nba-test',start_request_id:'launch-key-001',slate_date_et:'2026-10-20',run_mode:'BOTH',source_commit:'a'.repeat(40),eligible_game_ids:['4019999999'],fixture_locks:{},qbase_heads:{},created_at:'2026-10-20T10:00:00Z',status:'RESEARCH_IN_PROGRESS',completed_game_ids:[],research_checkpoints:{},freeze:null,invalidations:[],...overrides};}

test('same start request identity always derives the same run id',async()=>{const a=await deriveSlateRunId({requestId:'launch-key-001',slateDateEt:'2026-10-20',runMode:'BOTH'}),b=await deriveSlateRunId({requestId:'launch-key-001',slateDateEt:'2026-10-20',runMode:'BOTH'});assert.equal(a,b);assert.match(a,/^nba-[0-9a-f]{40}$/);});
test('new request key creates a distinct run identity for a genuine rerun',async()=>{const a=await deriveSlateRunId({requestId:'launch-key-001',slateDateEt:'2026-10-20',runMode:'BOTH'}),b=await deriveSlateRunId({requestId:'launch-key-002',slateDateEt:'2026-10-20',runMode:'BOTH'});assert.notEqual(a,b);});
test('Durable Object init is idempotent for an exact start retry',async()=>{const worker=new NbaSlateRun({storage:new MemoryStorage()},{}) ,s=state();let res=await worker.fetch(new Request('https://run/init',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({state:s,fixture_source:{provider:'test'}})}));assert.equal(res.status,200);let value=await res.json();assert.equal(value.idempotent_replay,false);res=await worker.fetch(new Request('https://run/init',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({state:s,fixture_source:{provider:'changed-but-ignored-on-retry'}})}));assert.equal(res.status,200);value=await res.json();assert.equal(value.idempotent_replay,true);assert.equal(value.run_id,'nba-test');});
test('Durable Object refuses a start-key collision with changed start payload',async()=>{const worker=new NbaSlateRun({storage:new MemoryStorage()},{}),s=state();await worker.fetch(new Request('https://run/init',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({state:s,fixture_source:null})}));const changed=state({run_mode:'ASSISTS_ONLY'});const res=await worker.fetch(new Request('https://run/init',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({state:changed,fixture_source:null})}));assert.equal(res.status,422);const value=await res.json();assert.match(value.error,/start request payload changed/);});
